from pathlib import Path
import hashlib
OLD=Path('/workspace/hdblast-research-work/continuation-next-20261007/release-planning');OUT=Path(__file__).resolve().parent
(OUT/'controller-review').mkdir(exist_ok=True)
b=(OLD/'controller_boundary_tests.py').read_text();(OUT/'controller_boundary_tests.py').write_text(b)
s=(OLD/'controller-review/offline_tests.py').read_text()
s=s.replace('The injected synthetic baseline preserves the required 23-file count and total.\nIts last large file is checked through immutable IDs rather than allocated bytes.', 'The injected synthetic baseline has 27 small manufactured files.\nAll 29 edition files undergo fresh fake content streams in both states.\nThese are test data; their total is not the live 448387915-byte inventory.')
s=s.replace('"2026.10.03-verified-source-operator"','M.PRIOR_SEMANTIC_VERSION')
s=s.replace('"parent": {"id": "999" if self.wrong_family and not prior else M.PARENT_ID}', '"parent": {"id": "999" if self.wrong_family and not prior else M.PARENT_ID, "access":{"owned_by":{"user":str(M.EXPECTED_OWNER)}}}')
s=s.replace('range(23)','range(27)').replace('range(4)','range(2)')
s=s.replace('        old[-1]["bytes"] = 440222994 - sum(x["bytes"] for x in old[:-1])\n        self.payloads.pop(old[-1]["filename"])\n','')
s=s.replace('"concept_id": 17088132, "current_record": 23114217', '"concept_id": 17088132, "current_record": 23225288, "expected_bytes":sum(x["bytes"] for x in old)')
s=s.replace('"PASS_COMPLETE_REMOTE_BYTES_MD5_SHA256"','"PASS_PRIOR_COMPLETE_BYTES_WITH_FRESH_IMMUTABLE_IDENTITY"')
s=s.replace('"publisher": "Zenodo", "copyright": "Fixture", "languages": [{"id": "eng"}]}', '"publisher": "Zenodo", "copyright": "Fixture", "languages": [{"id": "eng"}], "publication_date":"2026-10-07", "additional_descriptions":[{"description":"<p>New notes.</p>","lang":{"id":"eng"},"type":{"id":"notes"}},{"description":"<p>Preserved old notes.</p>","type":{"id":"notes"}}],"related_identifiers":[{"identifier":"10.5281/zenodo.23114217","scheme":"doi","relation_type":{"id":"references"},"resource_type":{"id":"software"}}]}')
s=s.replace('"expected_total_files_if_four_additions_finalized": 27', '"expected_total_files_final": 29, "scientific_replay_status": M.SCIENTIFIC_REPLAY_STATUS')
s=s.replace('self.root.joinpath("evidence/STATE.json").unlink()', '(self.root / "evidence").rename(self.root / "evidence-preserved-first-form")')
s=s.replace('result["file_count"], 27','result["file_count"], 29').replace('len(self.server.files), 23','len(self.server.files), 27').replace('len(self.server.files),27','len(self.server.files),29')
s=s.replace('len(self.posts("/commit")), 4','len(self.posts("/commit")), 2').replace('len(self.posts("/commit")),4','len(self.posts("/commit")),2')
s=s.replace('len(files), 12','len(files), 6')
s=s.replace('for method,url,headers in self.server.calls),4','for method,url,headers in self.server.calls),2')
s=s.replace('endswith("/draft/files")]),4','endswith("/draft/files")]),2')
s=s.replace('for x in result["content"]), 4','for x in result["content"]), 29')
s=s.replace('for c in self.server.calls), 4','for c in self.server.calls), 2')
s=s.replace('test_metadata_only_retry_keeps_four_completed_uploads','test_metadata_only_retry_keeps_two_completed_uploads')
s=s.replace('"SYNTHETIC_INJECTED_23_FILES_440222994_BYTES"','"SYNTHETIC_INJECTED_27_SMALL_FILES_ALL29_FAKE_STREAMED"')
# Imported files must acquire links for their fresh draft before reconciliation.
s=s.replace('        self.server.files = clone(self.server.old_files)\n        self.server.owner_pages', '        self.server.files = clone(self.server.old_files)\n        for name,f in self.server.files.items():f["links"]["content"]=f"{M.ORIGIN}/api/records/{DRAFT}/draft/files/{name}/content"\n        self.server.owner_pages')
(OUT/'controller-review/offline_tests.py').write_text(s)
print('flow_suite_sha256',hashlib.sha256(s.encode()).hexdigest())
