#!/usr/bin/env python3
"""Registered variational and independent complex-step classical response."""
import argparse, datetime, hashlib, json, time, traceback
from pathlib import Path
import numpy as np
import scipy
from scipy.integrate import solve_ivp

ROOT=Path(__file__).resolve().parent
EH=-1.3366923651588084e-23; YB=30.276680395885563
DELTA=.001; C=.5975949350280132; LN10=np.log(10.)
# Exact U(1+e) coefficients generated by expansion of W=1-phi+phi^3/3.
UC=np.array([-2/27,0,14/9,50/27,-1/6,-4/9,-2/27])
DC=[UC]+[np.array([np.prod(np.arange(j-k+1,j+1))*UC[j] for j in range(k,7)]) for k in range(1,4)]
def U(e,k=0): return np.polynomial.polynomial.polyval(e,DC[k])
def sigma(e): return 2/3+2*e*e+2/3*e**3+DELTA*(1+C*(1+e))
def sig1(e): return 4*e+2*e*e+DELTA*C
def sig2(e): return 4*(1+e)

def cone(eh,y,variational):
    u,up,upp,uppp=[U(eh,k) for k in range(4)]
    a=-u/36; b=u*u/4320-up*up/750; c=up/10; d=up*(upp/280+u/630)
    base=[y+a*y**3+b*y**5,eh+c*y*y+d*y**4,2*c*y+4*d*y**3]
    if not variational:return np.array(base)
    eh_l=LN10*eh
    al=-up*eh_l/36; bl=(u*up/2160-up*upp/375)*eh_l
    cl=upp*eh_l/10; dl=(upp*(upp/280+u/630)+up*(uppp/280+up/630))*eh_l
    A=al*y**3+bl*y**5; f=eh_l+cl*y*y+dl*y**4; g=2*cl*y+4*dl*y**3
    integ=al*y**5/5+(bl+a*al)*y**7/7
    return np.array(base+[A,f,g,integ])

def rhs(y,state):
    r,e,w=state[:3]; p=np.sqrt(1+r*r*(w*w/12-U(e)/6)); q=p/r
    out=[p,w,U(e,1)-4*q*w]
    if len(state)==7:
        A,f,g,I=state[3:]
        pl=(r*A*(w*w/12-U(e)/6)+r*r*(w*g-U(e,1)*f)/12)/p
        ql=pl/r-p*A/r**2
        out += [pl,g,U(e,2)*f-4*(ql*w+q*g),r*A]
    return out

def base_observables(state):
    r,e,w=state[:3]; h2=1/r**2; p=np.sqrt(1+r*r*(w*w/12-U(e)/6));q=p/r
    return np.array([q-sigma(e)/6,w+sig1(e)/2,e,h2])

def summarize(state):
    r,e,w,A,f,g,I=state
    h2=1/r**2;q=np.sqrt(h2+w*w/12-U(e)/6)
    pl=rhs(YB,state)[3]; ql=pl/r-q*A/r
    E1=q-sigma(e)/6;E2=w+sig1(e)/2
    direct=ql-sig1(e)*f/6
    integ=-2*I/r**4-E2*f/3
    h2l=-2*A/r**3
    wprime=U(e,1)-4*q*w
    j_y=[-h2-w*w/3-sig1(e)*w/6,wprime+sig2(e)*w/2]
    J=np.array([[integ,j_y[0]],[g+sig2(e)*f/2,j_y[1]]])
    output=np.array([[f,w],[h2l,-2*h2*q]])
    response=np.linalg.solve(J,np.diag([1/6,-1/2]))
    obs_response=output@response
    # Constraint differentiated at the endpoint: D H² = Aphi Dphi + sigma/18 s - sigma'/24 t.
    aphi=sigma(e)*sig1(e)/18-sig1(e)*sig2(e)/24+U(e,1)/6
    constraint_response=aphi*obs_response[0]+np.array([sigma(e)/18,-sig1(e)/24])
    return dict(R=float(r),phi=float(1+e),eta=float(e),w=float(w),H2=float(h2),q=float(q),
        residual=[float(E1),float(E2)],phi_ell=float(f),H2_ell=float(h2l),R_ell=float(A),
        E1_ell_direct=float(direct),E1_ell_integral=float(integ),integral=float(I),
        integral_identity_error=float(direct-integ),endpoint_exact_identities=[float(-h2),float((wprime/w+sig2(e)/2)*w)],
        J=J.tolist(),output_J=output.tolist(),coordinate_response=response.tolist(),observable_response=obs_response.tolist(),
        constraint_response=constraint_response.tolist(),constraint_response_error=(obs_response[1]-constraint_response).tolist(),
        determinant=float(np.linalg.det(J)),condition_number=float(np.linalg.cond(J)))

def run(method,rtol,y0,max_step=.1):
    t=time.time();sol=solve_ivp(rhs,(y0,YB),cone(EH,y0,True),method=method,rtol=rtol,atol=[1e-14]+[1e-100]*6,max_step=max_step)
    if not sol.success:raise RuntimeError(sol.message)
    return dict(method=method,rtol=rtol,y0=y0,max_step=max_step,nfev=sol.nfev,seconds=time.time()-t,**summarize(sol.y[:,-1]))

def complex_step(h):
    t=time.time();eh=EH*np.exp(1j*h*LN10);y0=1e-4
    sol=solve_ivp(rhs,(y0,YB),cone(eh,y0,False),method='DOP853',rtol=3e-14,atol=[1e-14,1e-100,1e-100],max_step=.1)
    if not sol.success:raise RuntimeError(sol.message)
    deriv=base_observables(sol.y[:,-1]).imag/h
    return dict(method='complex_step',h=h,seconds=time.time()-t,nfev=sol.nfev,E1_ell=float(deriv[0]),E2_ell=float(deriv[1]),phi_ell=float(deriv[2]),H2_ell=float(deriv[3]))

def verify_pins(repo):
    pins=json.loads((ROOT/'INPUT_PINS.json').read_text())
    for key,val in pins.items():
        p=ROOT/'REGISTRATION.md' if key=='registration' else repo/key
        assert hashlib.sha256(p.read_bytes()).hexdigest()==val['sha256'],str(p)

def main():
    p=argparse.ArgumentParser();p.add_argument('--repo',type=Path,default=Path('/workspace/HDblast'));p.add_argument('--output',type=Path,default=ROOT/'RUNS.json');args=p.parse_args()
    verify_pins(args.repo)
    out=dict(started_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),source_sha256=hashlib.sha256(Path(__file__).read_bytes()).hexdigest(),numpy=np.__version__,scipy=scipy.__version__,runs=[],failures=[])
    cases=[('DOP853',rt,y,.1) for rt in (1e-10,1e-12,3e-14) for y in (1e-2,1e-3,1e-4,1e-5)]
    cases += [('DOP853',3e-14,1e-5,.05)]+[('Radau',rt,y,.1) for rt in (1e-10,1e-12) for y in (1e-3,1e-4)]
    for case in cases:
        try:
            r=run(*case);out['runs'].append(r);print(case,'J00=',r['E1_ell_integral'],'identity=',r['integral_identity_error'],flush=True)
        except Exception:
            out['failures'].append(dict(case=case,error=traceback.format_exc()));print('FAILED',case,flush=True)
        args.output.write_text(json.dumps(out,indent=2)+'\n')
    for h in (1e-15,1e-20):
        try:out['runs'].append(complex_step(h));print('complex_step',h,out['runs'][-1],flush=True)
        except Exception:out['failures'].append(dict(case=['complex_step',h],error=traceback.format_exc()))
        args.output.write_text(json.dumps(out,indent=2)+'\n')
    out['completed_utc']=datetime.datetime.now(datetime.timezone.utc).isoformat();args.output.write_text(json.dumps(out,indent=2)+'\n')

if __name__=='__main__':main()
