import sympy as S
L,W=S.symbols('L W', positive=True)
h=S.symbols('h0:7',real=True)
k2=W*W-2*L*L
D=lambda f:S.expand(L*L*S.diff(f,L)+2*L**3/W*S.diff(f,W)+sum(h[i+1]*S.diff(f,h[i]) for i in range(6)))
def norm(f):return S.expand(f)
def plus(a,b):return (norm(a[0]+b[0]),norm(a[1]+b[1]))
def neg(a):return(-a[0],-a[1])
def sub(a,b):return plus(a,neg(b))
def mul(a,b):return(norm(a[0]*b[0]),norm(a[0]*b[1]+a[1]*b[0]))
def power(a,n):return(norm(a[0]**n),norm(n*a[0]**(n-1)*a[1]))
def div(a,b):return mul(a,power(b,-1))
def scale(a,b):return(norm(a[0]*b),norm(a[1]*b))
def deriv(a):return(D(a[0]),D(a[1]))
ell=(L,h[1]); omega=(W,2*L*L*h[0]/W); T=(2*L*L,2*L*h[1]+h[2]); wp=deriv(omega);wpp=deriv(wp)
U=plus(plus(scale(div(T,omega),-S.Rational(1,2)),scale(div(wpp,power(omega,2)),-S.Rational(1,4))),scale(div(power(wp,2),power(omega,3)),S.Rational(3,8)))
Up=deriv(U); Upp=deriv(Up)
V=plus(plus(plus(plus(scale(div(power(U,2),omega),-S.Rational(1,2)),scale(div(Upp,power(omega,2)),-S.Rational(1,4))),scale(div(mul(wpp,U),power(omega,3)),S.Rational(1,4))),scale(div(mul(wp,Up),power(omega,3)),S.Rational(3,4))),scale(div(mul(power(wp,2),U),power(omega,4)),-S.Rational(3,4)))
b=(-k2/3-2*L*L,-4*L*L*h[0]);c=sub((1,0),div(b,power(omega,2)))
J2=plus(div(mul(ell,wp),power(omega,2)),scale(div(power(wp,2),power(omega,3)),S.Rational(1,4)))
J4=plus(plus(plus(div(mul(ell,Up),power(omega,2)),scale(div(mul(mul(ell,wp),U),power(omega,3)),-2)),scale(div(mul(wp,Up),power(omega,3)),S.Rational(1,2))),scale(div(mul(power(wp,2),U),power(omega,4)),-S.Rational(3,4)))
r0=scale(omega,S.Rational(1,2));p0=scale(div((k2,0),omega),S.Rational(1,6))
r2=scale(plus(div(power(ell,2),omega),J2),S.Rational(1,4));p2=scale(plus(plus(mul(c,U),div(power(ell,2),omega)),J2),S.Rational(1,4))
r4=scale(plus(sub(div(power(U,2),omega),div(mul(power(ell,2),U),power(omega,2))),J4),S.Rational(1,4))
p4=scale(plus(sub(plus(mul(c,V),div(mul(b,power(U,2)),power(omega,3))),div(mul(power(ell,2),U),power(omega,2))),J4),S.Rational(1,4))
for name,r,p in [('zero',r0,p0),('two',r2,p2),('four',r4,p4)]:
 ward=sub(plus(deriv(r),scale(mul(ell,p),3)),mul(ell,r))
 print(name,'baseline',S.factor(ward[0]),'variation',S.factor(ward[1]))
Nr=plus(plus(r0,r2),r4);Np=plus(plus(p0,p2),p4);Fq=sub(scale(power(omega,-1),S.Rational(1,2)),scale(div(U,power(omega,2)),S.Rational(1,2)))
g=4*L*L*h[0]-2*L*h[1]-h[2];g1=D(g);g2=D(g1)
wm=(0,g/(2*W));wm1=deriv(wm);wm2=deriv(wm1)
# Mass variation of adiabatic U2, U4, and J4 at fixed metric.
dUm=g/(2*W);dUm1=D(dUm);dUm2=D(dUm1)
dVm=-U[0]*dUm/W-dUm2/(4*W**2)+wpp[0]*dUm/(4*W**3)+3*wp[0]*dUm1/(4*W**3)-3*wp[0]**2*dUm/(4*W**4)
dJm=L*dUm1/W**2-2*L*wp[0]*dUm/W**3+wp[0]*dUm1/(2*W**3)-3*wp[0]**2*dUm/(4*W**4)
dNrm=S.expand((g/W+2*U[0]*dUm/W-g*U[0]/W**2-L*L*dUm/W**2+dJm)/4)
dNpm=S.expand((c[0]*dUm-g/W+c[0]*dVm+2*b[0]*U[0]*dUm/W**3+g*U[0]/W**2-L*L*dUm/W**2+dJm)/4)
print('VAR_Q_DIFF',S.factor(Fq[1]+g/(4*W**3)))
print('NR_DIFF',S.collect(S.expand(Nr[1]-dNrm),W))
print('NP_DIFF',S.collect(S.expand(Np[1]-dNpm),W))
print('BASE_R',S.collect(Nr[0],W))
print('BASE_P',S.collect(Np[0],W))
v=S.symbols('v',positive=True)
K2=2*L*L*v*v/(1-v*v); KW=2*L*L*v/(1-v*v)
Rlead=S.factor((K2*K2+3*L*L*K2-KW*(K2+2*L*L))/8+L**4*v/2)
Plead=S.factor((K2*K2-3*L*L*K2+KW*(-K2+4*L*L))/24-L**4*v/3)
I={n:S.expand((2*L*L)**S.Rational(3-n,2)*sum((-1)**j*S.binomial((n-5)//2,j)*v**(2*j+3)/S.Integer(2*j+3) for j in range((n-5)//2+1))) for n in range(5,16,2)}
def integrate_high(expr):
 expanded=S.expand(expr)
 return S.expand(sum(expanded.coeff(W,-n)*I[n] for n in I))
Rbase=S.factor(Rlead-integrate_high(Nr[0]));Pbase=S.factor(Plead-integrate_high(Np[0]))
QR=S.factor(integrate_high(Fq[1]+g/(4*W**3)))
ER=S.factor((L*h[1]+h[2]/4)*L*L*v*v/(1+v)-integrate_high(Nr[1]-dNrm))
EP=S.factor(-h[2]/4*L*L*v*v/(1+v)-integrate_high(Np[1]-dNpm))
print('RLEAD',Rlead,'PLEAD',Plead)
print('RBASE_CLOSED',Rbase,'PBASE_CLOSED',Pbase)
print('QDIFF_INT',QR,'RDIFF_INT',ER,'PDIFF_INT',EP)
print('CONTINUUM_BASE',S.simplify(Rbase.subs(v,1)),S.simplify(Pbase.subs(v,1)))
print('CONTINUUM_EXTRA',S.simplify(QR.subs(v,1)),S.simplify(ER.subs(v,1)),S.simplify(EP.subs(v,1)))
