"""Machine-readable record of literature sweep 1 (theory) for the HDBLAST checkpoint of 27 Sept 2026.

Every URL below appeared in the result list of the WebSearch query (or queries) named in `queries`.
No page on arxiv.org, zenodo.org, link.springer.com, uu.diva-portal.org or www.uu.se could be opened
(WebFetch returned EGRESS_BLOCKED), so every `finding` paraphrases a search-result snippet only.
Snippets are machine-written summaries and can be wrong; see `caveat` where conflicts were noticed.
Authors are listed only when a snippet named them.
"""

QUERIES = [
    "Emergent de Sitter cosmology from decaying anti-de Sitter space Banerjee Danielsson Dibitetto Giri Schillo",  # 1
    "\"dark bubble\" braneworld cosmology Danielsson 2024 OR 2025",  # 2
    "Karch Randall \"locally localized gravity\" de Sitter brane AdS",  # 3
    "ekpyrotic universe colliding branes big bang Khoury Ovrut Steinhardt Turok",  # 4
    "\"Dark bubbles, dark dimensions and fat gravitons\"",  # 5
    "\"Dark bubble cosmology and the equivalence principle\" 2507.03748",  # 6
    "\"Weak gravity at micron scales from dark bubble cosmology\" Danielsson Giri",  # 7
    "\"The dark bubbleography\" Banerjee Danielsson Zemsch non-normalizable modes",  # 8
    "dark bubble nucleation catalyzed by five-dimensional black hole quantum origin of the universe",  # 9
    "\"Dark bubbles and black holes\" Danielsson Dibitetto Giri AdS5 nucleation",  # 10
    "\"Out of the white hole\" holographic origin for the Big Bang Pourhasan Afshordi Mann 5D black hole",  # 11
    "Garriga Sasaki \"Brane-world creation and black holes\" de Sitter brane AdS instanton",  # 12
    "Gen Sasaki \"Radion on the de Sitter brane\" negative mass squared",  # 13
    "thick de Sitter brane stability scalar field domain wall Kobayashi Koyama Soda",  # 14
    "stability of de Sitter domain walls bulk scalar superpotential perturbations curved domain wall 2023-2025",  # 15
    "DeWolfe Freedman Gubser Karch \"Modeling the fifth dimension with scalars and gravity\"",  # 16
    "\"Fake supergravity and domain wall stability\" Freedman Nunez Schnabl Skenderis",  # 17
    "\"Can inflating braneworlds be stabilized\" de Sitter brane radion",  # 18
    "Kaloper \"Bent domain walls as braneworlds\" de Sitter brane AdS5",  # 19
    "Takamizu Maeda collision of domain walls reheating of the brane universe colliding branes numerical",  # 20
    "de Sitter swampland conjecture review 2024 2025 status Obied Ooguri Spodyneiko Vafa trans-Planckian censorship",  # 21
    "\"dark dimension\" Montero Vafa Valenzuela micron extra dimension cosmological constant 2022",  # 22
    "non-supersymmetric AdS vacua unstable Ooguri Vafa conjecture bubble nucleation brane Brown-Teitelboim",  # 23
    "holographic reheating braneworld particle production brane energy transfer bulk 2023 OR 2024 OR 2025",  # 24
    "universe emerged from higher-dimensional black hole brane 2025 study Big Bang fifth dimension",  # 25
    "\"de Sitter cosmology on an expanding bubble\" Banerjee Danielsson Dibitetto Giri Schillo JHEP 2019",  # 26
    "Antonini Swingle Van Raamsdonk end-of-the-world brane cosmology from AdS",  # 27
    "Hawking Hertog Reall \"Brane new world\" de Sitter brane AdS created from nothing CFT",  # 28
    "\"Brane cosmology from AdS/BCFT\" end-of-the-world brane scalar field big bang",  # 29
    "\"Effective Dynamics of Inflationary End-of-the-World Branes\"",  # 30
    "\"Dynamical dark energy in 0'B braneworlds\" Basile",  # 31
    "cyclic universe brane collision 2024 2025 new work Ijjas Steinhardt bounce higher dimensional",  # 32
    "Garriga Vilenkin perturbations on domain walls de Sitter wall fluctuation tachyonic mode nucleated bubble",  # 33
    "\"Born-Again Braneworld\" Kanno Sasaki Soda radion de Sitter brane",  # 34
    "Randall Sundrum \"An alternative to compactification\" 1999 single brane AdS5",  # 35
    "Binetruy Deffayet Langlois \"Non-conventional cosmology from a brane-universe\" rho squared Friedmann dark radiation",  # 36
    "de Sitter brane Kaluza-Klein graviton spectrum mass gap (3/2)H Randall-Sundrum inflating brane",  # 37
    "Koyama Takahashi bulk inflaton de Sitter brane scalar cosmological perturbations exactly solvable model",  # 38
    "Maartens Koyama \"Brane-World Gravity\" Living Reviews in Relativity",  # 39
    "Kiritsis Kofinas Tetradis Tomaras Zarikas \"Cosmological evolution with brane-bulk energy exchange\"",  # 40
    "\"Primordial Correlators from a Kaluza-Klein Graviton Continuum\"",  # 41
    "\"Regular collision of dilatonic inflating branes\"",  # 42
    "numerical relativity bubble collisions observational signatures Johnson Peiris Lehner Wainwright eternal inflation CMB",  # 43
    "\"De Sitter space constraints on brane tensions and couplings\"",  # 44
    "\"Shedding light on dark bubble cosmology\" radiation brane Maxwell",  # 45
    "\"de Sitter bubbles and the swampland\" 2008.07555",  # 46
    "\"Catalytic creation of a bubble universe induced by quintessence in five dimensions\"",  # 47
    "Skenderis Townsend \"Hidden supersymmetry of domain walls and cosmologies\" curved domain walls superpotential",  # 48
    "Giovannini \"gauge-invariant fluctuations of scalar branes\" thick brane stability",  # 49
    "Charmousis Gregory Rubakov \"Wave function of the radion in a brane world\" brane bending ghost",  # 50
    "Garriga \"Smooth creation of an open universe in five dimensions\"",  # 51
    "\"Cosmological perturbations in the 5D Big Bang\" Tolley Turok",  # 52
    "Takamizu Kudoh Maeda \"Dynamics of colliding branes and black brane production\" AdS bulk",  # 53
    "\"The String Landscape, the Swampland and the Observed Universe\" Agmon Bedroya Kang Vafa",  # 54
    "\"Self-gravitating electromagnetic waves in the dark bubble model\"",  # 55
    "\"On the Origin and Fate of Our Universe\" 2501.00966",  # 56
    "\"Cosmological Perturbations in the 5D Holographic Big Bang Model\" 1703.00954",  # 57
    "\"Dark bubbles: decorating the wall\" string cloud matter on bubble",  # 58
    "\"Gravitational waves in dark bubble cosmology\" Danielsson Giri Panizo",  # 59
    "\"What's the (Dark) Matter with Cosmological Bubbles\"",  # 60 (result off-topic; not used)
    "dark bubble Vilenkin tunneling wave function quantum cosmology nucleation of brane AdS5 Danielsson",  # 61
    "ekpyrotic slow contraction numerical relativity robustness initial conditions Ijjas Cook Pretorius Steinhardt",  # 62
    "double holography de Sitter brane Karch-Randall braneworld 2023 2024 2025 induced gravity dS brane AdS bulk",  # 63
    "Kraus \"Dynamics of anti-de Sitter domain walls\" brane in AdS-Schwarzschild bulk black hole mass dark radiation",  # 64
    "Savonije Verlinde \"CFT and entropy on the brane\" Friedmann equation Cardy-Verlinde brane moving AdS black hole",  # 65
    "Horowitz Orgera Polchinski \"Nonperturbative instability of AdS5 x S5/Zk\" bubble of nothing",  # 66
    "our universe bubble expanding in fifth dimension new study 2026 cosmology string theory",  # 67
    "\"When do colliding bubbles produce an expanding universe\" Gratton Turok",  # 68
    "\"De Sitter versus Anti de Sitter flows and the (super)gravity landscape\"",  # 69
    "\"Stability of non-supersymmetric vacua from calibrations\" brane nucleation AdS",  # 70
    "Witten \"Instability of the Kaluza-Klein vacuum\" bubble of nothing 1982",  # 71
    "Ghosh Kiritsis Nitti Witkowski \"De Sitter and Anti-de Sitter branes in self-tuning models\"",  # 72
    "Ghosh Kiritsis Nitti Witkowski \"Holographic RG flows on curved manifolds and quantum phase transitions\"",  # 73
    "Charmousis Kiritsis Nitti \"holographic self-tuning of the cosmological constant\" brane Einstein-dilaton",  # 74
    "Kiritsis Tsouros 2025 2026 Einstein-scalar dS AdS flows \"Centaur\" no regular solutions interpolating",  # 75
    "\"Nucleation of de Sitter from the anti de Sitter spacetime in scalar field models\"",  # 76
    "\"Holographic confining theories on space-times with constant positive curvature\" Kiritsis",  # 77
    "\"Brane cosmology and the self-tuning of the cosmological constant\" Kiritsis Nitti Amariti Ghosh",  # 78
    "\"Scalar stars and lumps with (A)dS core\" Einstein-scalar",  # 79 (not used)
    "\"Self-sustained, out-of-equilibrium inflation\" holographic",  # 80
    "holographic reheating strongly coupled sector de Sitter thermalization end of inflation AdS/CFT 2024 2025 arXiv",  # 81
    "Lehners Turok \"Bouncing negative-tension branes\" OR \"M-theory model of a big crunch/big bang transition\"",  # 82
    "Nihei OR \"Kim and Kim\" inflation on the brane de Sitter brane AdS5 tension exceeds critical Hubble rate formula 1999",  # 83
    "\"A dynamical inflaton coupled to strongly interacting matter\" holography reheating",  # 84
    "\"Inflation with a growing fifth dimension\" dark dimension",  # 85
    "\"Gravitational reheating at strong coupling\" 2304.11195",  # 86
    "brane world dark radiation BBN constraint bulk Weyl C/a^4 2023 2024 N_eff braneworld constraint",  # 87
    "BraneCode numerical code brane world dynamics bulk scalar five-dimensional simulations",  # 88
    "\"End-of-the-World Branes and Inflationary Predictions for Rocky and Swampy Landscapes\"",  # 89
    "\"Curing with hemlock\" escaping the swampland using instabilities from string theory dark bubble",  # 90
    "\"Colliding bubble worlds\" Gen Ishihara Sasaki braneworld big bang bubble collision 5D",  # 91
    "de Sitter brane bulk scalar field linear stability perturbations 2025 OR 2026 arXiv warped braneworld tachyon radion single brane",  # 92
    "Afshordi holographic big bang 5D black hole collapse brane 2024 OR 2025 update",  # 93
    "particle production nucleated bubble wall brane universe expanding bubble reheating quantum fields on bubble wall",  # 94
    "\"The global structure of the colliding bubble braneworld universe\" OR \"A braneworld universe from colliding bubbles\" Bucher",  # 95
    "\"Brane big bang brought on by a bulk bubble\"",  # 96
    "\"Coupled bulk and brane fields about a de Sitter brane\" radion sqrt(2)H normalizable single brane",  # 97
    "Shiromizu Maeda Sasaki \"The Einstein equations on the 3-brane world\" projected Weyl tensor",  # 98
    "Coleman De Luccia \"Gravitational effects on and of vacuum decay\" bubble nucleation AdS true vacuum crunch",  # 99
    "\"Crunch from AdS bubble collapse in unbounded potentials\"",  # 100
    "\"Generalized surface tension bounds in vacuum decay\" Espinosa superpotential tunneling potential",  # 101
    "\"Searching for Coleman-de Luccia bubbles in AdS compactifications\"",  # 102
    "\"Features of a dark energy model in string theory\" dark bubble 2212.14004",  # 103
    "\"Dark energy from string theory: an introductory review\" 2603.25797",  # 104
    "\"Bubbles of cosmology in AdS/CFT\" Sahu Simidzija Van Raamsdonk",  # 105
    "\"Revisiting Coleman-de Luccia transitions in the AdS regime using holography\"",  # 106
    "\"Nothing really matters\" JHEP 2020 bubble of nothing dark bubble",  # 107
    "\"higher-dimensional blast\" Big Bang hypothesis five-dimensional brane Maldonado",  # 108
    "Garriga Tanaka \"Gravity in the Randall-Sundrum brane world\" linearized gravity brane bending",  # 109
    "\"The big bang as a higher-dimensional shock wave\" Kaluza-Klein",  # 110
    "\"Solution of a Braneworld Big Crunch/Big Bang Cosmology\" McFadden Turok Steinhardt five-dimensional dynamics",  # 111
]

S = "search-snippet-only"

SOURCES = [
    # ---------------- A. Dark bubble programme (de Sitter on a wall from decaying AdS5) ----------------
    dict(id="A1", theme="A", title="Emergent de Sitter Cosmology from Decaying Anti-de Sitter Space",
         authors="S. Banerjee, U. Danielsson, G. Dibitetto, S. Giri, M. Schillo", year="2018",
         venue="Phys. Rev. Lett. 121, 261301; arXiv:1807.01570", url="https://arxiv.org/abs/1807.01570",
         finding="Proposes that positive-energy FLRW cosmology arises on a brane (bubble wall) that mediates the decay of a non-supersymmetric false AdS5 vacuum to a true vacuum; 4D gravity is confined on the brane and a 4D observer sees an effective positive cosmological constant coupled to matter and radiation, without scale separation or a fundamental de Sitter vacuum.",
         relevance="The best-developed published precedent for 'our universe is an expanding codimension-one wall in 5D AdS with de Sitter induced on it'. Unlike HDBLAST it has different AdS5 vacua on the two sides (no Z2 doubling) and the creation event is a quantum nucleation, not a classical roll-off of a registered shell.",
         implication="context", access=S, queries=[1]),
    dict(id="A2", theme="A", title="de Sitter Cosmology on an expanding bubble",
         authors="S. Banerjee, U. Danielsson, G. Dibitetto, S. Giri, M. Schillo", year="2019",
         venue="JHEP 10 (2019) 164; arXiv:1907.04268", url="https://arxiv.org/abs/1907.04268",
         finding="Develops the 4D cosmology on a codimension-one bubble wall separating two AdS5 vacua, relates the scenario to the weak gravity conjecture, and interprets the de Sitter temperature as the Unruh temperature of an accelerated observer riding the bubble.",
         relevance="The Unruh-temperature reading applies equally to the HDBLAST static shells (temperature H/2pi of the dS slicing). It is a vacuum temperature of an empty de Sitter brane, not a radiation era, so it does not remove the HDBLAST negative result.",
         implication="context", access=S, queries=[26]),
    dict(id="A3", theme="A", title="Dark bubbles: decorating the wall",
         authors="S. Banerjee, U. Danielsson, S. Giri", year="2020",
         venue="JHEP 04 (2020) 085; arXiv:2001.07433", url="https://arxiv.org/abs/2001.07433",
         finding="Adds matter and radiation to the dark bubble, treating backreaction in the bulk and on the brane through brane bending, and computes the backreacted metric on the bent brane and in the 5D bulk.",
         relevance="A worked template for the sector HDBLAST lacks: brane matter that backreacts consistently on a 5D wall geometry. The 22 Sept HDBLAST matter extension has the same goal but has not been evolved.",
         implication="method", access=S, queries=[58]),
    dict(id="A4", theme="A", title="Curing with hemlock: escaping the swampland using instabilities from string theory",
         authors="S. Banerjee and colleagues (full author list not in snippet)", year="2021",
         venue="arXiv:2103.17121 (snippet names Int. J. Mod. Phys. D)", url="https://arxiv.org/abs/2103.17121",
         finding="Argues that a dark bubble with strings attached can carry our universe out of the swampland, using the instabilities of apparently hostile corners of the swampland; dark energy and possibly other dark components are presented as features of higher-dimensional physics.",
         relevance="States the dark-bubble response to swampland objections. HDBLAST has no string embedding, so it can neither use nor be excluded by this argument yet.",
         implication="context", access=S, queries=[90]),
    dict(id="A5", theme="A", title="Gravitational waves in dark bubble cosmology",
         authors="U. Danielsson and co-authors (snippet)", year="2022",
         venue="Phys. Rev. D 106, 024002; arXiv:2202.00545", url="https://arxiv.org/abs/2202.00545",
         finding="Constructs the 5D uplift of 4D gravitational waves in de Sitter cosmology on a nucleated bubble in AdS5, extends the link between dark bubbles and Vilenkin's quantum cosmology to gravitational perturbations, and explains apparently negative energy contributions in the 4D Einstein equations that distinguish the dark bubble from Randall-Sundrum.",
         relevance="Method for uplifting tensor perturbations on a nucleated wall. A related snippet (query 61) states that bubble-nucleation boundary conditions select the Vilenkin weighting; that is the kind of weighting any HDBLAST 'creation event' would need.",
         implication="method", access=S, queries=[59, 61]),
    dict(id="A6", theme="A", title="Features of a dark energy model in string theory",
         authors="S. Banerjee, U. Danielsson, S. Giri", year="2023",
         venue="Phys. Rev. D 108, 126009; arXiv:2212.14004", url="https://arxiv.org/abs/2212.14004",
         finding="Clears up misconceptions about the dark bubble: points out important differences from Randall-Sundrum and explains why gravity neither is, nor needs to be, localized on the dark bubble.",
         relevance="HDBLAST is Randall-Sundrum-like: a Z2 doubled bulk closed off by a regular cone, so the bulk volume is finite. Its 4D gravity mechanism therefore differs from the dark bubble's, and results cannot be transferred between the two without care.",
         implication="context", access=S, queries=[103]),
    dict(id="A7", theme="A", title="Shedding light on dark bubble cosmology",
         authors="I. Basile, U. Danielsson, S. Giri, D. Panizo", year="2023",
         venue="JHEP 02 (2024) 112; arXiv:2310.15032", url="https://arxiv.org/abs/2310.15032",
         finding="Incorporates electromagnetic fields: worldvolume fields backreact on the ambient 5D universe, changing the energy-momentum distribution and the effective gravity induced on the brane, and the resulting 4D cosmology consistently contains electromagnetic waves.",
         relevance="Shows that radiation on a wall must source bulk fields for consistency. In HDBLAST the only bulk fields are the metric and phi, so a radiation era would need an analogous consistent bulk source (for example a bulk black hole or Weyl term).",
         implication="method", access=S, queries=[45]),
    dict(id="A8", theme="A", title="Experimental tests of dark bubble cosmology",
         authors="U. Danielsson, D. Panizo (snippet)", year="2024",
         venue="Phys. Rev. D 109, 026003; arXiv:2311.14589", url="https://link.aps.org/doi/10.1103/PhysRevD.109.026003",
         finding="The snippet gives only the title, authors and journal; no result is summarized here.",
         relevance="Listed so that the testability line of the dark bubble programme is not missed; content not assessed.",
         implication="context", access=S, queries=[2, 9]),
    dict(id="A9", theme="A", title="The dark bubbleography",
         authors="S. Banerjee, U. Danielsson, M. Zemsch", year="2024",
         venue="JHEP 02 (2024) 102; arXiv:2311.16242", url="https://arxiv.org/abs/2311.16242",
         finding="Presents the holographic construction of the dark bubble and shows, following holographic renormalization, that non-normalizable modes are essential for a vanishing induced graviton mass in any braneworld model; applies this to the propagator on the wall.",
         relevance="The claim is stated for 'any braneworld model'. HDBLAST's compact regular-cone bulk has a normalizable zero mode, and its tensor sector was found mode-stable (Chat 12). How these two statements fit together should be checked before HDBLAST claims 4D graviton behaviour.",
         implication="method", access=S, queries=[8]),
    dict(id="A10", theme="A", title="Dark bubble cosmology and the equivalence principle",
         authors="I. Basile, A. Borys, J. Masias", year="2025",
         venue="arXiv:2507.03748; Phys. Rev. D (2026)", url="https://arxiv.org/abs/2507.03748",
         finding="Couples the electroweak and strong sectors to the induced braneworld gravity by the dark-bubble mechanism. The electroweak sector is unaffected, but the proton's gravitational and inertial masses differ significantly, severely violating equivalence-principle measurements.",
         relevance="A sharp negative test that any braneworld with bulk-mediated matter couplings must pass. HDBLAST's proposed matter field chi has a phi-dependent mass, so the bulk scalar couples directly to brane matter; an equivalence-principle and fifth-force check is required before that extension can be called viable.",
         implication="challenges", access=S, queries=[6, 2],
         caveat="Snippets disagree on the journal reference: one gives Phys. Rev. D 113 (2026) issue 2, another wrongly attaches Phys. Rev. D 109, 026003 (which belongs to A8). The programme's Chat 9 prior-art file records Phys. Rev. D 113, 026009."),
    dict(id="A11", theme="A", title="Weak gravity at micron scales from dark bubble cosmology and its cosmological consequences",
         authors="U. Danielsson, S. Giri", year="2025",
         venue="arXiv:2511.21362; Phys. Rev. D (2026)", url="https://arxiv.org/abs/2511.21362",
         finding="Predicts that gravity becomes weaker, not stronger, than Newtonian at about 1e-5 m, with explicit table-top predictions. The same effect lowers effective gravity at high energy densities and gives early inflation with nothing beyond radiation. The paper also discusses a quantum origin of the universe in which a 5D black hole of critical size catalyses nucleation of the dark bubble at its horizon, and the black hole's matter becomes the matter on the bubble.",
         relevance="This is the closest recent published proposal to 'a five-dimensional event created our universe'. It also supplies what HDBLAST lacks: a source of matter, the catalysing black hole. HDBLAST cannot claim the general concept as new and should cite this line of work.",
         implication="context", access=S, queries=[7, 9]),
    dict(id="A12", theme="A", title="Dark bubbles, dark dimensions and fat gravitons",
         authors="U. Danielsson, S. Giri", year="2026",
         venue="arXiv:2606.20942 (18 June 2026)", url="https://arxiv.org/abs/2606.20942",
         finding="Uses the instabilities behind the de Sitter swampland conjectures to make accelerated expansion inevitable. The dark bubble is presented as a realization of the dark-dimension proposal and of Sundrum's fat graviton. Predictions: a micron-size dark dimension, gravity fading at micron distances, a string scale of tens of TeV, and a measurable positive spatial curvature.",
         relevance="Shows the kind of falsifiable output this class of model can produce. HDBLAST has no such prediction yet. Positive spatial curvature is natural for a closed de Sitter slicing, which HDBLAST's static shells also use; this is a possible future observable, but it is not derived for HDBLAST.",
         implication="context", access=S, queries=[5, 1]),
    dict(id="A13", theme="A", title="Self-gravitating electromagnetic waves in the dark bubble model",
         authors="U. Danielsson and one co-author (snippet)", year="2026",
         venue="arXiv:2606.16547 (15 June 2026)", url="https://arxiv.org/abs/2606.16547",
         finding="Embeds gravitational and electromagnetic waves using AdS5 pp-wave geometries glued across a three-brane. For localized light beams under mixed AdS5 boundary conditions, the gravitational corrections are consistent with 4D gravity weakening at the 5D AdS scale. On the brane, electromagnetic waves source the Kalb-Ramond B-field in the bulk.",
         relevance="Exact wall-plus-radiation solutions of this type could serve as analytic benchmarks for any HDBLAST radiation-on-shell calculation.",
         implication="method", access=S, queries=[55]),
    dict(id="A14", theme="A", title="Dynamical dark energy in 0'B braneworlds",
         authors="I. Basile and two co-authors (snippet)", year="2025",
         venue="Eur. Phys. J. C (Sept 2025); arXiv:2502.20438", url="https://arxiv.org/abs/2502.20438",
         finding="Builds a dark-bubble realization in non-supersymmetric type 0'B string theory, the unique scale-separated option among the simplest models. The dark energy varies logarithmically. The blue-shifted spectrum excludes inflation, the late-time predictions conflict with Standard Model couplings, and the model appears not to be phenomenologically viable.",
         relevance="A concrete example of a 5D-wall cosmology failing when fully specified, published as a negative result. It sets the standard of candour HDBLAST follows.",
         implication="challenges", access=S, queries=[31]),
    # ---------------- B. Creation, nucleation, catalysis, bubbles of nothing ----------------
    dict(id="B1", theme="B", title="Brane-world creation and black holes",
         authors="J. Garriga, M. Sasaki", year="2000",
         venue="Phys. Rev. D 62, 043523; arXiv:hep-th/9912118", url="https://arxiv.org/abs/hep-th/9912118",
         finding="An inflating brane-world can be created from nothing with its AdS bulk. The spatial sections are compact and bounded by the brane, and the de Sitter brane instanton has its interior filled with AdS. The paper discusses Nariai-like pair creation of 'black cigars', and finds that 5D and 4D actions and entropies agree when the instanton is much larger than the AdS radius. Thermal instantons with an AdS black hole in the bulk may describe the creation of a hot universe from nothing.",
         relevance="HDBLAST's static geometry is this instanton's Lorentzian section with a bulk scalar added: a dS-sliced AdS region closed off by a regular cone, Z2-doubled, with one brane. The thermal-instanton variant is a documented route to a hot initial state through a bulk black hole. HDBLAST has not tried it.",
         implication="method", access=S, queries=[12, 37]),
    dict(id="B2", theme="B", title="Brane New World",
         authors="S. W. Hawking, T. Hertog, H. S. Reall", year="2000",
         venue="Phys. Rev. D 62, 043501; arXiv:hep-th/0003052", url="https://arxiv.org/abs/hep-th/0003052",
         finding="A Randall-Sundrum domain wall in AdS with a strongly coupled large-N CFT on it. The conformal anomaly acts as an effective tension that gives the wall de Sitter geometry, the analogue of Starobinsky inflation. The graviton correlator is computed from the no-boundary proposal, and the CFT strongly suppresses metric perturbations on all but the largest angular scales.",
         relevance="An alternative quantum origin of a de Sitter brane in AdS, with a holographic matter sector and a perturbation prediction. It is a benchmark for any HDBLAST perturbation spectrum (open item 5).",
         implication="context", access=S, queries=[28]),
    dict(id="B3", theme="B", title="Smooth 'creation' of an open universe in five dimensions",
         authors="J. Garriga", year="1998",
         venue="arXiv:hep-th/9804106", url="https://arxiv.org/abs/hep-th/9804106",
         finding="A non-singular 5D instanton for creating an open universe with a compact extra dimension. Its 4D section is a singular Hawking-Turok instanton, and the 'singularity' is a smooth 5D bubble of nothing. Flat space with a compact extra dimension is gravitationally metastable, but long-lived if the extra dimension is much larger than the Planck length.",
         relevance="Conceptual precedent: a smooth higher-dimensional event can look like a 4D singularity. This supports the logic of looking for a 5D cause of a 4D Big Bang, but it is a different mechanism.",
         implication="context", access=S, queries=[51]),
    dict(id="B4", theme="B", title="Catalytic creation of a bubble universe induced by quintessence in five dimensions",
         authors="I. Koga, Y. Ookouchi", year="2020",
         venue="Phys. Rev. D 104, 126015 (2021); arXiv:2011.07437", url="https://arxiv.org/abs/2011.07437",
         finding="Studies 5D bubble nucleation catalysed by quintessence, in the decay of a metastable Minkowski vacuum to AdS, and the dynamics of the bubble that carries a 4D expanding universe. Also discusses the trans-Planckian censorship conjecture and proposes mechanisms for inflation and dark energy.",
         relevance="Precedent for catalysed creation of a 4D universe on a 5D bubble. The related 2019 paper 'Catalytic Creation of Baby Bubble Universe with Small Positive Cosmological Constant' (arXiv:1909.03014) appeared in the same result list.",
         implication="context", access=S, queries=[47]),
    dict(id="B5", theme="B", title="dS4 universe emergent from Kerr-AdS5 spacetime: bubble nucleation catalyzed by a black hole",
         authors="not captured in snippet", year="2022",
         venue="JHEP 05 (2023) 107; arXiv:2209.05625", url="https://arxiv.org/abs/2209.05625",
         finding="Studies nucleation of a vacuum bubble in Kerr-AdS5, sufficient conditions for nucleation with a rotating black hole, and how the black hole changes the transition rate; the bubble carries an emergent dS4 universe.",
         relevance="Quantitative black-hole-catalysed creation rates for a dS4 wall in AdS5. It is the closest rate calculation to a '5D event creating our universe'.",
         implication="context", access=S, queries=[9, 10]),
    dict(id="B6", theme="B", title="Dark bubbles and black holes",
         authors="not reliably captured in snippet", year="2021",
         venue="JHEP 09 (2021) 158", url="https://link.springer.com/article/10.1007/JHEP09(2021)158",
         finding="Only the title and venue are reliable from the snippets. The accompanying summary text mixed content from several dark-bubble and catalysis papers (black-hole- and string-cloud-catalysed vacuum decay; charged Nariai black holes on the dark bubble), so no specific finding is attributed here.",
         relevance="Part of the black-hole-plus-dark-bubble line (see A11, B5).",
         implication="context", access=S, queries=[10, 58],
         caveat="Snippet summary was not attributable to this paper alone."),
    dict(id="B7", theme="B", title="Out of the White Hole: A Holographic Origin for the Big Bang",
         authors="R. Pourhasan, N. Afshordi, R. B. Mann", year="2013",
         venue="JCAP 04 (2014) 005; arXiv:1309.1487", url="https://arxiv.org/abs/1309.1487",
         finding="In a DGP braneworld (4D induced gravity plus 5D bulk gravity), the universe emerges as a spherical 3-brane from the formation of a 5D Schwarzschild black hole. The holographic fluid's pressure singularity lies inside the white-hole horizon and need not be physical. A thermal atmosphere at about 20% of the 5D Planck mass can induce scale-invariant curvature perturbations without inflation.",
         relevance="A prominent published model of a 5D gravitational event producing the Big Bang, with its own perturbation mechanism. It is major prior art for the HDBLAST headline idea.",
         implication="context", access=S, queries=[11]),
    dict(id="B8", theme="B", title="Cosmological Perturbations in the 5D Holographic Big Bang Model",
         authors="N. Altamirano, E. Gould, N. Afshordi, R. B. Mann", year="2017",
         venue="arXiv:1703.00954", url="https://arxiv.org/abs/1703.00954",
         finding="Computes the exact curvature power spectrum from a thin atmosphere accreting onto the 3-brane. It is scale-invariant on small scales, red on intermediate scales and blue beyond the atmosphere height, and is marginally disfavoured against a simple power law (2.7 sigma). A 2025 snippet (query 93) reports a best-fit nucleation temperature at least three orders of magnitude above the 5D Planck mass, and a 2025 book chapter, 'Cosmic Bubbles and the 5D Holographic Big Bang Model'.",
         relevance="Shows how a 5D-origin model is confronted with CMB data, and that doing so can produce tension. HDBLAST has no spectrum yet (open item 5).",
         implication="constrains", access=S, queries=[57, 93]),
    dict(id="B9", theme="B", title="Nucleation of de Sitter from the anti de Sitter spacetime in scalar field models",
         authors="M. Cadoni, M. Pitzalis, A. P. Sanna", year="2024",
         venue="Eur. Phys. J. C (2025); arXiv:2407.10469", url="https://arxiv.org/abs/2407.10469",
         finding="In Einstein-scalar gravity, gravitational coupling can drive nucleation of de Sitter from AdS through a static, spherically symmetric, metastable scalar lump. Euclidean actions and free energies are compared: the AdS lump is generally less favoured, and the most preferred state is a de Sitter vacuum.",
         relevance="A worked Euclidean-action comparison in Einstein-scalar gravity. The same comparison between HDBLAST's two static branches (cone near phi=-1 versus near phi=+1) has not been done and is cheap.",
         implication="method", access=S, queries=[76]),
    dict(id="B10", theme="B", title="Revisiting Coleman-de Luccia transitions in the AdS regime using holography",
         authors="J. K. Ghosh, E. Kiritsis, F. Nitti, L. T. Witkowski", year="2021",
         venue="JHEP (Sept 2021); arXiv:2102.11881", url="https://arxiv.org/abs/2102.11881",
         finding="Coleman-de Luccia AdS-to-AdS decays in Einstein-scalar theories are interpreted as vev-driven holographic RG flows of a QFT on de Sitter space. These flows do not exist for generic potentials; that is the holographic statement that gravity can stabilise false AdS vacua. Existence of the tunnelling solutions is tied to exotic RG flows, and explicit potentials admitting them are constructed.",
         relevance="HDBLAST's static solutions belong to exactly this class: Einstein-scalar solutions with de Sitter slicing and a regular endpoint where the slice shrinks. The existence and classification criteria bear directly on the open existence and uniqueness question for the +1 branch.",
         implication="method", access=S, queries=[106]),
    dict(id="B11", theme="B", title="Searching for Coleman-de Luccia bubbles in AdS compactifications",
         authors="G. Dibitetto, N. Petri", year="2022",
         venue="Phys. Rev. D 107, 046020 (2023); arXiv:2207.02172", url="https://arxiv.org/abs/2207.02172",
         finding="Fully backreacted gravitational instantons are obtained by numerically integrating first-order Hamilton-Jacobi equations: smooth domain walls with de Sitter foliations connecting a supersymmetric and a non-supersymmetric AdS vacuum, showing a nonperturbative instability of the latter.",
         relevance="The same mathematics as HDBLAST, a superpotential (Hamilton-Jacobi) description of dS-foliated walls, applied in truncations of string theory. It is a numerical method and a possible cross-check for HDBLAST's static-branch solver.",
         implication="method", access=S, queries=[102]),
    dict(id="B12", theme="B", title="Nothing really matters",
         authors="G. Dibitetto, N. Petri, M. Schillo", year="2020",
         venue="JHEP 08 (2020) 040", url="https://ui.adsabs.harvard.edu/abs/2020JHEP...08..040D/abstract",
         finding="Constructs gravitational instantons that generalise Witten's bubble of nothing to AdS with a cosmological constant in any dimension. Their expansion is described by a lower-dimensional de Sitter geometry within a non-compact foliation. Covariantly constant spinors are discussed as a possible topological obstruction to such decays.",
         relevance="An alternative 'higher-dimensional blast': a bubble of nothing in AdS whose wall is de Sitter. The spinor obstruction matters if HDBLAST's W is ever derived from a supersymmetric theory.",
         implication="context", access=S, queries=[107]),
    dict(id="B13", theme="B", title="Instability of the Kaluza-Klein vacuum",
         authors="E. Witten", year="1982",
         venue="Nucl. Phys. B 195, 481", url="https://ui.adsabs.harvard.edu/abs/1982NuPhB.195..481W/abstract",
         finding="The Kaluza-Klein ground state is unstable to semiclassical barrier penetration (the bubble of nothing), because the positive-energy conjecture fails for Kaluza-Klein theory; elementary fermions would stabilise it.",
         relevance="The foundational example of a higher-dimensional vacuum event with a de Sitter-like expanding wall.",
         implication="context", access=S, queries=[71]),
    dict(id="B14", theme="B", title="Nonperturbative Instability of AdS5 x S5/Zk",
         authors="G. T. Horowitz, J. Orgera, J. Polchinski", year="2007",
         venue="Phys. Rev. D 77, 024004 (2008); arXiv:0709.4262", url="https://arxiv.org/abs/0709.4262",
         finding="For a freely acting, supersymmetry-breaking orbifold there are no tachyons at large 't Hooft coupling, yet a nonperturbative bubble-of-nothing instability analogous to Kaluza-Klein vacuum decay exists.",
         relevance="Non-supersymmetric AdS5 backgrounds are generically suspect in string theory. Any future string embedding of HDBLAST's bulk vacua would face this.",
         implication="context", access=S, queries=[66]),
    dict(id="B15", theme="B", title="Gravitational Effects on and of Vacuum Decay",
         authors="S. Coleman, F. De Luccia", year="1980",
         venue="Phys. Rev. D (1980); journal details not in snippet",
         url="https://www.semanticscholar.org/paper/Gravitational-Effects-on-and-of-Vacuum-Decay-Coleman-Luccia/a60b863946ca2d85da9d8b48b72257e8ec05e3ed",
         finding="As summarised in the snippet: gravity can prevent the decay of a Minkowski or AdS false vacuum; in the thin-wall limit this happens when the wall tension exceeds a bound proportional to the difference of the square roots of the two vacuum energy densities.",
         relevance="HDBLAST's balanced tension sigma=2W is the critical, BPS-like tension at which a flat wall exists (checked exactly in theory_checks: 2W = 6/ell at both vacua). The registered detuning delta>0 is supercritical, which is why the static shells are de Sitter branes.",
         implication="context", access=S, queries=[99],
         caveat="Year from general knowledge; the snippet gave title and authors only."),
    dict(id="B16", theme="B", title="Generalized surface tension bounds in vacuum decay",
         authors="A. Masoumi, S. Paban, E. J. Weinberg", year="2017",
         venue="arXiv:1711.06776", url="https://arxiv.org/abs/1711.06776",
         finding="Some thin walls have a curvature radius that changes substantially across the wall, so the Coleman-de Luccia tension is ill-defined. The paper proposes a tension definition for this regime, shows it obeys a CDL-like bound, and derives a general bound for all bounces with Minkowski or AdS false vacua.",
         relevance="Gives a principled way to define an effective shell tension when the scalar is nonconstant across the wall, as on HDBLAST's +1 branch.",
         implication="method", access=S, queries=[101]),
    dict(id="B17", theme="B", title="Crunch from AdS bubble collapse in unbounded potentials",
         authors="not captured in snippet", year="2024",
         venue="arXiv:2411.07692 (Nov 2024)", url="https://arxiv.org/abs/2411.07692",
         finding="Classical evolution of an AdS bubble nucleated from a Minkowski false vacuum in a potential with an infinitely deep true vacuum along a quartic slope. The interior collapses and forms a spacelike curvature singularity behind an apparent horizon. The scalar's kinetic energy overtakes the negative potential energy, the core density turns positive and trapped surfaces form. This requires no lower bound on the potential.",
         relevance="HDBLAST's potential is also unbounded below (U ~ -(2/27) phi^6 at large |phi|, checked exactly in theory_checks). Its Chat 13 drafts wrongly blamed the reversal on this; the corrected cause is sub-balanced tension. This paper supplies the right diagnostic for the collapse fate: search for trapped surfaces and an apparent horizon.",
         implication="method", access=S, queries=[100]),
    dict(id="B18", theme="B", title="End-of-the-World Branes and Inflationary Predictions for Rocky and Swampy Landscapes",
         authors="B. Hassfeld, A. Hebecker, A. Westphal", year="2024",
         venue="JHEP 03 (2025) 196; arXiv:2411.11944", url="https://arxiv.org/abs/2411.11944",
         finding="A framework for anthropic predictions assuming de Sitter vacua have finite-dimensional Hilbert spaces. Even with eternal inflation, predictions depend on the rates of creating universes from nothing, and these rates are highly sensitive to the existence of end-of-the-world branes. Distinguishes 'swampy' from 'rocky' landscapes.",
         relevance="Any claim that a 5D event is a typical origin of our universe depends on creation-rate measures. HDBLAST has not addressed measures.",
         implication="constrains", access=S, queries=[89]),
    dict(id="B19", theme="B", title="Bubbles of cosmology in AdS/CFT",
         authors="A. Sahu, P. Simidzija, M. Van Raamsdonk", year="2023",
         venue="JHEP (Nov 2023); arXiv:2306.13143", url="https://arxiv.org/abs/2306.13143",
         finding="The typical big-bang/big-crunch cosmologies of holographic effective theories are not asymptotically AdS, but arbitrarily large spherical bubbles of them can be embedded in asymptotically AdS spacetimes with a Schwarzschild-AdS exterior.",
         relevance="A holographic framing in which a cosmological region is bounded by a shell with a black-hole exterior. It is a possible interpretation of a future HDBLAST shell with a bulk black-hole mass.",
         implication="context", access=S, queries=[105]),
    # ---------------- C. Brane/bubble collisions, ekpyrotic and cyclic ----------------
    dict(id="C1", theme="C", title="The Ekpyrotic Universe: Colliding Branes and the Origin of the Hot Big Bang",
         authors="J. Khoury, B. A. Ovrut, P. J. Steinhardt, N. Turok", year="2001",
         venue="Phys. Rev. D 64, 123522; arXiv:hep-th/0103239", url="https://arxiv.org/html/hep-th/0103239v2",
         finding="The hot big bang is produced when a bulk brane collides with a bounding orbifold plane, starting from a cold, empty, static universe. The scenario is claimed to address the horizon, flatness and monopole problems and to give a nearly scale-invariant spectrum without inflation.",
         relevance="Canonical prior art for 'a higher-dimensional event makes the hot Big Bang'. HDBLAST must cite it and state how it differs: a single Z2 shell in a registered Einstein-scalar bulk, with no second brane or orbifold plane.",
         implication="context", access=S, queries=[4]),
    dict(id="C2", theme="C", title="M theory model of a big crunch/big bang transition",
         authors="N. Turok, M. Perry, P. J. Steinhardt", year="2004",
         venue="Phys. Rev. D 70, 106004", url="https://ui.adsabs.harvard.edu/abs/2004PhRvD..70j6004T/abstract",
         finding="Treats a big crunch/big bang transition as the collision of two empty orbifold planes and shows that p-brane states winding around the extra dimension propagate smoothly across the collision.",
         relevance="Shows how a 5D collision can be continued through; relevant if HDBLAST's collapse fate is ever continued past the singularity.",
         implication="context", access=S, queries=[82]),
    dict(id="C3", theme="C", title="Cosmological perturbations in a big crunch/big bang space-time",
         authors="A. J. Tolley, N. Turok, P. J. Steinhardt", year="2004",
         venue="Phys. Rev. D 69, 106005; arXiv:hep-th/0306109", url="https://arxiv.org/pdf/hep-th/0306109",
         finding="A prescription for matching general-relativistic perturbations across collision singularities of orbifold planes, of the kind met in ekpyrotic and cyclic scenarios.",
         relevance="A matching method for perturbations across a 5D collision event.",
         implication="method", access=S, queries=[52]),
    dict(id="C4", theme="C", title="Solution of a Braneworld Big Crunch/Big Bang Cosmology",
         authors="P. McFadden, N. Turok, P. J. Steinhardt", year="2005",
         venue="Phys. Rev. D 76, 104038 (2007); arXiv:hep-th/0512123", url="https://arxiv.org/abs/hep-th/0512123",
         finding="Solves for perturbations around two separating or colliding boundary branes as an expansion in the collision speed (V/c). The 4D effective description fails at the first nontrivial order, (V/c)^2, where the growing and decaying 4D modes mix nontrivially.",
         relevance="A warning for HDBLAST: its closed-form 4D effective theory agrees with 5D to about 1e-6 for the static tachyon, but may fail near fast events (turnaround, collapse). This supports keeping full 5D evolution as the reference.",
         implication="constrains", access=S, queries=[111]),
    dict(id="C5", theme="C", title="Bouncing Negative-Tension Branes",
         authors="J.-L. Lehners, N. Turok", year="2007",
         venue="Phys. Rev. D 77, 023516 (2008); arXiv:0708.0743", url="https://arxiv.org/pdf/0708.0743",
         finding="The snippet gives the bibliographic record only.",
         relevance="Listed for completeness of the brane-collision line.",
         implication="context", access=S, queries=[82]),
    dict(id="C6", theme="C", title="A new kind of cyclic universe",
         authors="A. Ijjas, P. J. Steinhardt", year="2019",
         venue="arXiv:1904.08022", url="https://arxiv.org/abs/1904.08022",
         finding="Ekpyrotic contraction combined with a non-singular classical bounce: H, energy density and temperature oscillate while the scale factor grows exponentially from cycle to cycle. A companion snippet says the earlier colliding-brane models have given way to bouncing models built from ordinary 4D scalar fields.",
         relevance="The ekpyrotic programme itself moved from 5D brane collisions to 4D bounces. This is context for how strong the 5D evidence would need to be.",
         implication="context", access=S, queries=[32]),
    dict(id="C7", theme="C", title="Robustness of slow contraction to cosmic initial conditions",
         authors="A. Ijjas, W. G. Cook, F. Pretorius, P. J. Steinhardt, G. N. Davies", year="2020",
         venue="arXiv:2006.04999", url="https://arxiv.org/abs/2006.04999",
         finding="Numerical-relativity simulations vary all freely specifiable initial data (shear, curvature, scalar field and velocity profiles), including data far outside the perturbative regime, and find slow contraction robust. A follow-up (arXiv:2104.12293) finds robustness enhanced with multiple modes and reduced symmetry.",
         relevance="A methodological template for testing whether HDBLAST's two fates are robust to non-perturbative initial disturbances. The balanced two-bump seeds so far cover a narrow family.",
         implication="method", access=S, queries=[62]),
    dict(id="C8", theme="C", title="A Braneworld Universe From Colliding Bubbles",
         authors="M. Bucher", year="2001",
         venue="Phys. Lett. B 530, 1 (2002); arXiv:hep-th/0107148", url="https://ar5iv.arxiv.org/html/hep-th/0107148",
         finding="The Big Bang hypersurface is the collision locus of two bubbles that nucleate in 5D flat space with AdS inside; the resulting domain wall localizes gravity as in Randall-Sundrum.",
         relevance="Prior art for a 5D nucleation-and-collision origin of an RS brane universe.",
         implication="context", access=S, queries=[95]),
    dict(id="C9", theme="C", title="Cosmological Perturbations Generated in the Colliding Bubble Braneworld Universe",
         authors="J. J. Blanco-Pillado, M. Bucher", year="2001",
         venue="Phys. Rev. D 65, 083517 (2002); arXiv:hep-th/0111089", url="https://arxiv.org/abs/hep-th/0111089",
         finding="Computes the perturbations in the colliding-bubble braneworld, where quantum fluctuations develop on the AdS-filled bubbles before they collide to form a Randall-Sundrum brane.",
         relevance="A method for primordial perturbations from a 5D origin event.",
         implication="method", access=S, queries=[95, 52]),
    dict(id="C10", theme="C", title="When do colliding bubbles produce an expanding universe?",
         authors="J. J. Blanco-Pillado and colleagues (snippet); Gratton and Turok are acknowledged, not authors", year="2003",
         venue="Phys. Rev. D 69, 103515 (2004); arXiv:hep-th/0306151", url="https://arxiv.org/abs/hep-th/0306151",
         finding="A symmetric collision leaves a collapsing universe on the final brane unless the bulk expansion rate just before the collision is large compared with the momentum transfer in the fifth dimension. That prior expansion can come from negative spatial curvature or a positive 5D cosmological constant. Thick-wall numerical collisions confirm the thin-wall result.",
         relevance="A published analogue of HDBLAST's two fates, expansion versus reversal and collapse, with an explicit criterion (expansion rate against fifth-dimension momentum transfer) that could be evaluated on the Chat 14 trajectories.",
         implication="method", access=S, queries=[68, 67]),
    dict(id="C11", theme="C", title="Brane Big-Bang Brought by Bulk Bubble",
         authors="not captured in snippet", year="2001",
         venue="Phys. Rev. D 66, 023519 (2002); arXiv:hep-th/0110286", url="https://arxiv.org/pdf/hep-th/0110286",
         finding="A brane first inflates because the bulk vacuum energy and the brane tension are mismatched, with the bulk in a false vacuum. Bulk false-vacuum decay nucleates a negative-energy true-vacuum bubble that expands, hits the brane and produces a hot Randall-Sundrum big-bang brane. Inflation ends because the bulk vacuum energy changes, and the bubble's kinetic energy heats the universe.",
         relevance="Very close to the HDBLAST narrative: a detuned, inflating brane plus a bulk event that ends inflation and reheats it. It shows that a 5D-event reheating mechanism has been proposed before, and it offers a concrete heating channel (wall kinetic energy deposited on the brane) that HDBLAST's vacuum roll-off lacks.",
         implication="supports", access=S, queries=[96, 94]),
    dict(id="C12", theme="C", title="Collision of Domain Walls and Reheating of the Brane Universe",
         authors="Y. Takamizu, K. Maeda", year="2004",
         venue="Phys. Rev. D 70, 123514; arXiv:hep-th/0406235", url="https://arxiv.org/abs/hep-th/0406235",
         finding="Particle production when two domain walls collide in 5D Minkowski space, proposed as the reheating mechanism of ekpyrotic or cyclic brane universes. As rendered in the snippet, the created energy density is about 20 g^4 N_b m^4 and the reheating temperature T_R is about 0.88 g N_b^(1/4), for coupling g, number of bounces N_b and wall mass scale m. A follow-up treats collisions in asymptotically AdS5 (arXiv:hep-th/0603076).",
         relevance="A calibrated wall-collision reheating estimate against which HDBLAST's formal production proxy (22 Sept matter extension) could be compared, once physical scales are chosen.",
         implication="method", access=S, queries=[20, 94],
         caveat="The formula's symbols were garbled in the snippet ('20g^4 N_mn^4'); the reading above is a best interpretation."),
    dict(id="C13", theme="C", title="Dynamics of colliding branes and black brane production",
         authors="Y. Takamizu, H. Kudoh, K. Maeda", year="2007",
         venue="Phys. Rev. D 75, 061304; arXiv:gr-qc/0702138", url="https://arxiv.org/abs/gr-qc/0702138",
         finding="Self-gravitating colliding domain walls, with initial data from a BPS wall in 5D supergravity, generically form a spacelike curvature singularity covered by a horizon: a black brane with trapped walls. Exceptions are non-relativistic weak-field cases, where the walls pass through each other or bounce several times.",
         relevance="Suggests a definite hypothesis for HDBLAST's collapse fate: black-brane formation with the shell trapped. It is testable with an apparent-horizon search on the Chat 14 runs.",
         implication="challenges", access=S, queries=[53]),
    dict(id="C14", theme="C", title="Born-Again Braneworld",
         authors="S. Kanno, M. Sasaki, J. Soda", year="2002",
         venue="Prog. Theor. Phys. 109, 357 (2003); arXiv:hep-th/0210250", url="https://arxiv.org/abs/hep-th/0210250",
         finding="Two inflating branes collide and re-emerge with tensions of opposite sign. The radion acts as the gravitational scalar; in the Einstein frame the scenario resembles pre-big-bang cosmology; vacuum gravitational waves have a very blue spectrum.",
         relevance="An example where radion (modulus) dynamics of inflating branes, rather than matter, drives the transition, as in HDBLAST's tachyonic roll-off.",
         implication="context", access=S, queries=[34]),
    dict(id="C15", theme="C", title="Regular collision of dilatonic inflating branes",
         authors="E. Leeper, K. Koyama, R. Maartens", year="2005",
         venue="Phys. Rev. D 73, 043506 (2006); arXiv:hep-th/0508145", url="https://arxiv.org/abs/hep-th/0508145",
         finding="A two-brane system with a bulk scalar driving power-law inflation on the branes has a radion instability that can lead to collision; brane quantities such as the scale factor stay regular at the collision; a low-energy expansion reproduces the exact solution.",
         relevance="Bulk-scalar inflating branes with a radion instability are established; HDBLAST's tachyonic shell mode is of this general type (in a single-shell, regular-cone geometry).",
         implication="supports", access=S, queries=[42]),
    dict(id="C16", theme="C", title="The big bang as a higher-dimensional shock wave",
         authors="P. S. Wesson, H. Liu, S. S. Seahra", year="2000",
         venue="Astron. Astrophys. 358, 425; arXiv:gr-qc/0003012", url="https://arxiv.org/pdf/gr-qc/0003012",
         finding="An exact solution of the 5D field equations describes a shock wave moving in time and the extra coordinate, suggesting the 4D big bang was a 5D shock wave. Different observers can measure different ages. The induced 4D spacetimes match standard FRW matter- and radiation-era models.",
         relevance="The earlier work whose wording is closest to 'higher-dimensional blast'. It uses a different framework, the induced-matter (space-time-matter) Kaluza-Klein approach, not a brane in an Einstein-scalar bulk, and should be cited to avoid a novelty claim on the phrase or the idea.",
         implication="context", access=S, queries=[110, 108]),
    dict(id="C17", theme="C", title="Simulating the universe(s) II: phenomenology of cosmic bubble collisions in full General Relativity",
         authors="Johnson, Peiris, Lehner and collaborators (per query context)", year="2014",
         venue="arXiv:1407.2950 (also arXiv:1112.4487, arXiv:1508.03641)", url="https://arxiv.org/pdf/1407.2950",
         finding="Full-GR simulations of bubble collisions, computing cosmological observables directly from the scalar Lagrangian; the first fully relativistic predictions for an ensemble of eternal-inflation models, which differ significantly from non-relativistic approximations.",
         relevance="Methodology for turning a violent, collision-type origin event into CMB templates, if HDBLAST ever reaches that stage.",
         implication="method", access=S, queries=[43],
         caveat="Exact author list per paper not given in snippet."),
    # ---------------- D. Randall-Sundrum / Karch-Randall foundations and brane cosmology ----------------
    dict(id="D1", theme="D", title="An Alternative to Compactification",
         authors="L. Randall, R. Sundrum", year="1999",
         venue="Phys. Rev. Lett. 83, 4690", url="https://ui.adsabs.harvard.edu/abs/1999PhRvL..83.4690R/abstract",
         finding="A single 3-brane in 5D AdS reproduces 4D Newtonian and general-relativistic gravity even without a Kaluza-Klein mass gap, because the warped bulk has finite volume.",
         relevance="The base model that HDBLAST's late-time static branch reduces to. The +1 branch is an RS de Sitter brane plus a small scalar-profile correction.",
         implication="context", access=S, queries=[35]),
    dict(id="D2", theme="D", title="Locally localized gravity",
         authors="A. Karch, L. Randall", year="2001",
         venue="JHEP 0105, 008", url="https://iopscience.iop.org/article/10.1088/1126-6708/2001/05/008",
         finding="An AdS4 brane in AdS5 has a bound-state graviton when the AdS4 cosmological constant is small, and the graviton has an ultrasmall mass. The brane can be Minkowski, de Sitter or AdS depending on its tension.",
         relevance="The tension classification behind HDBLAST: tension above the critical value gives a de Sitter brane. The theory_checks script verifies that the registered balanced tension 2W equals the critical value 6/ell at both AdS vacua, so delta(1+c phi)>0 is precisely the supercritical detuning.",
         implication="method", access=S, queries=[3]),
    dict(id="D3", theme="D", title="Bent Domain Walls as Braneworlds",
         authors="N. Kaloper", year="1999",
         venue="Phys. Rev. D 60, 123506; arXiv:hep-th/9905210", url="https://arxiv.org/pdf/hep-th/9905210",
         finding="Studies 3-brane domain walls in a curved 5D bulk that couple gravitationally to the bulk, including curved (de Sitter/AdS) walls, as braneworld models.",
         relevance="One of the original derivations of the de Sitter brane in AdS5. A snippet for query 83 quotes the thin-brane relation H^2 = (4 pi G5 sigma/3)^2 + Lambda5/6, attributing the related inflation analyses to Nihei (Phys. Lett. B 465 (1999) 81) and Kim and Kim (Phys. Rev. D 61, 064003). No direct URL to those two papers was obtained. In HDBLAST units this relation is H^2 = (sigma/6)^2 - 1/ell^2, which reproduces the checkpoint's H^2 expansion through O(delta), and through O(delta^2) apart from the -c^2 delta^2/384 scalar-profile term (theory_checks).",
         implication="method", access=S, queries=[19, 83]),
    dict(id="D4", theme="D", title="The Einstein Equations on the 3-Brane World",
         authors="T. Shiromizu, K. Maeda, M. Sasaki", year="1999",
         venue="arXiv:gr-qc/9910076 (journal details not in snippet)", url="https://arxiv.org/abs/gr-qc/9910076",
         finding="Derives the effective 4D Einstein equations on a Z2-symmetric brane in 5D Einstein gravity. The non-local bulk effect enters through the projected 5D Weyl tensor, a symmetric traceless tensor constrained by the Bianchi identities.",
         relevance="The standard way to see the bulk Weyl ('dark radiation') and bulk-scalar contributions to HDBLAST's shell Friedmann equation.",
         implication="method", access=S, queries=[98],
         caveat="Year inferred from the arXiv number."),
    dict(id="D5", theme="D", title="Dynamics of Anti-de Sitter Domain Walls",
         authors="P. Kraus", year="1999",
         venue="JHEP 12 (1999) 011; arXiv:hep-th/9910149", url="https://arxiv.org/abs/hep-th/9910149v1",
         finding="Moving domain walls in the Randall-Sundrum universe with the bulk patched together from AdS5 black-hole solutions; the junction equations fix the wall motion, which observers on the wall see as cosmological expansion or contraction.",
         relevance="An exact way to add a bulk black-hole mass behind a shell and obtain an a^-4 ('dark radiation') term. It is the simplest literature-backed extension HDBLAST has not tried.",
         implication="method", access=S, queries=[64]),
    dict(id="D6", theme="D", title="CFT and Entropy on the Brane",
         authors="I. Savonije, E. Verlinde", year="2001",
         venue="Phys. Lett. B (2001) (not in snippet)", url="https://www.semanticscholar.org/paper/CFT-and-Entropy-on-the-Brane-Savonije-Verlinde/7e51da58584a6054a76ef7e1d6c126e0c797e242",
         finding="A brane with fine-tuned tension moving in an AdS black-hole background carries a radiation-dominated closed FRW universe, the radiation being the thermal CFT dual to the bulk black hole; when the brane crosses the horizon the Friedmann equation coincides with the Cardy(-Verlinde) entropy formula.",
         relevance="Gives the holographic meaning of the a^-4 term from a bulk black hole (item D5). It is a candidate 'hot' ingredient for HDBLAST, with the caveat that this radiation is a hidden CFT sector, not Standard Model radiation.",
         implication="supports", access=S, queries=[65],
         caveat="Journal and year not given in snippet; year from general knowledge."),
    dict(id="D7", theme="D", title="Gravity in the Randall-Sundrum Brane World",
         authors="J. Garriga, T. Tanaka", year="1999",
         venue="arXiv:hep-th/9911055", url="https://arxiv.org/abs/hep-th/9911055",
         finding="A single positive-tension wall recovers Einstein gravity at leading order, with Kaluza-Klein corrections. With two branes of opposite tension, gravity is linearized Brans-Dicke; on the positive-tension wall the BD parameter exceeds 3000 if the separation is more than 4 AdS radii.",
         relevance="Sets the benchmark for gravity on HDBLAST's late-time shell, and indicates what a scalar (radion-like) admixture would do to 4D tests.",
         implication="method", access=S, queries=[109]),
    dict(id="D8", theme="D", title="Brane-World Gravity",
         authors="R. Maartens, K. Koyama", year="2010",
         venue="Living Rev. Relativ. 13, 5; arXiv:1004.3962", url="https://arxiv.org/abs/1004.3962",
         finding="A review of the geometry, dynamics and perturbations of warped 5D brane-worlds, mainly Randall-Sundrum based.",
         relevance="A standard reference for conventions (junctions, Weyl term, perturbations) when comparing HDBLAST with the literature.",
         implication="context", access=S, queries=[39]),
    dict(id="D9", theme="D", title="Modeling the fifth dimension with scalars and gravity",
         authors="O. DeWolfe, D. Z. Freedman, S. S. Gubser, A. Karch", year="1999",
         venue="Phys. Rev. D 62, 046008 (2000); arXiv:hep-th/9909134", url="https://arxiv.org/pdf/hep-th/9909134",
         finding="A first-order (superpotential) method for 5D scalar-plus-gravity solutions, inspired by gauged supergravity but not requiring supersymmetry; applied to a full nonlinear treatment of interbrane stabilization; any effectively compactified fifth dimension contains a massless graviton.",
         relevance="HDBLAST's registered model uses exactly this structure: U = (1/2)W_phi^2 - (2/3)W^2, phi' = W_phi, A' = -W/3, balanced tension 2W. The theory_checks script verifies that the first-order flow solves the Einstein equations from the metric, and that the kink phi = -tanh y solves phi' = W_phi. The registered model is therefore a detuned DeWolfe-Freedman-Gubser-Karch wall.",
         implication="method", access=S, queries=[16]),
    dict(id="D10", theme="D", title="Cosmological evolution with brane-bulk energy exchange",
         authors="E. Kiritsis, G. Kofinas, N. Tetradis, T. N. Tomaras, V. Zarikas", year="2002",
         venue="JHEP 2003; arXiv:hep-th/0207060", url="https://arxiv.org/abs/hep-th/0207060",
         finding="Energy exchange between brane and bulk produces a rich variety of brane cosmologies depending on the transfer mechanism, the equation of state and the spatial topology; an accelerating era is generic.",
         relevance="Classification template for HDBLAST's proposed exchange law rho_dot + 3H(rho+p) = j phi_dot.",
         implication="method", access=S, queries=[40]),
    dict(id="D11", theme="D", title="Reheating the Universe in Braneworld Cosmological Models with bulk-brane energy transfer",
         authors="not captured in snippet", year="2008",
         venue="arXiv:0805.1792", url="https://arxiv.org/abs/0805.1792",
         finding="Analyses how the cosmological composition emerges (the reheating era) after inflation in 5D braneworld models with brane-bulk energy exchange.",
         relevance="A direct precedent for the reheating calculation HDBLAST still needs (open item 4).",
         implication="method", access=S, queries=[24]),
    dict(id="D12", theme="D", title="Observational Constraints on Dark Radiation in Brane Cosmology",
         authors="not captured in snippet", year="2002",
         venue="Phys. Rev. D 66, 043521; arXiv:astro-ph/0203272", url="https://arxiv.org/abs/astro-ph/0203272",
         finding="Big Bang nucleosynthesis limits brane dark radiation (the bulk Weyl a^-4 term) to -1.23 <= rho_d/rho_gamma <= 0.11 at BBN; adding CMB constraints narrows this to -0.41 <= rho_d/rho_gamma <= 0.105. The same snippet also quotes a range of -12.1% to +6.2% of the total density at 10 MeV, possibly from another paper.",
         relevance="Any HDBLAST 'hot' ingredient built from a bulk black hole or Weyl term must satisfy these bounds. By itself it cannot be the radiation era, which must be mostly Standard Model radiation.",
         implication="constrains", access=S, queries=[87]),
    # ---------------- E. Stability of dS-sliced walls and branes ----------------
    dict(id="E1", theme="E", title="Perturbations on domain walls and strings: A covariant theory",
         authors="J. Garriga, A. Vilenkin", year="1991",
         venue="Phys. Rev. D 44, 1007", url="https://journals.aps.org/prd/abstract/10.1103/PhysRevD.44.1007",
         finding="A covariant formalism for perturbations of walls and strings, including nucleated true-vacuum bubbles and walls in de Sitter space. The perturbation field often has a tachyonic mass and a nonminimal coupling to the worldsheet curvature. Ignoring gravity, one scalar describes the wall's translations. Local observers see perturbations grow; external observers see them freeze.",
         relevance="Tachyonic masses on de Sitter walls can partly reflect wall translation, which is not a physical instability. HDBLAST's certified tachyon (mu^2 between -7.71788 and -7.71786 in units of H^2) was analysed with the full linearized equations in Chats 11-12, which also clarified the status of the 'mu^2 = -4' harmonics. This paper is the classic reference for separating wall-translation modes from physical instabilities.",
         implication="method", access=S, queries=[33]),
    dict(id="E2", theme="E", title="Radion on the de Sitter brane",
         authors="U. Gen, M. Sasaki", year="2000",
         venue="arXiv:gr-qc/0011078", url="https://arxiv.org/pdf/gr-qc/0011078",
         finding="With two de Sitter branes of opposite tension, the radion has a negative mass squared proportional to the brane curvature. With a single positive-tension de Sitter brane there is no radion, and ordinary Einstein gravity is recovered with massive KK corrections.",
         relevance="Explains why HDBLAST's tachyon cannot be a pure-gravity radion: HDBLAST has one shell, and the regular cone is not a second brane. The instability must come from the bulk scalar and its tension coupling, which agrees with the Chat 9 effective theory.",
         implication="supports", access=S, queries=[13]),
    dict(id="E3", theme="E", title="Can Inflating Braneworlds be Stabilized?",
         authors="A. Frolov, L. Kofman (from the programme's Chat 9 prior-art file, which read the paper; not in this snippet)", year="2003",
         venue="arXiv:hep-th/0309002", url="https://arxiv.org/abs/hep-th/0309002v1",
         finding="For de Sitter branes the radion mass squared is typically negative, a strong tachyonic instability, so the parameters of 'stabilized' inflating braneworlds are constrained; BraneCode numerics confirm the instability; the flat-brane limit recovers the usual positive radion mass. A related result (Phys. Rev. D 67, 063515) stabilizes dS and AdS braneworlds with the Casimir force.",
         relevance="In the literature, tachyonic moduli of de Sitter branes are generic. HDBLAST's registered-shell tachyon is typical rather than anomalous, and its stable shell S_8/5 (curved tension, d = 8/5) is an instance of evading the generic instability.",
         implication="supports", access=S, queries=[18]),
    dict(id="E4", theme="E", title="Wave function of the radion in a brane world",
         authors="C. Charmousis, R. Gregory, V. A. Rubakov", year="1999",
         venue="Phys. Rev. D 62, 067505 (2000); arXiv:hep-th/9912160", url="https://arxiv.org/abs/hep-th/9912160",
         finding="Computes the linearized radion in the two-brane Randall-Sundrum model and its couplings to matter on each brane, in agreement with Garriga-Tanaka.",
         relevance="A reference construction of scalar metric modes; useful when interpreting any HDBLAST shell-scalar coupling to brane matter.",
         implication="method", access=S, queries=[50]),
    dict(id="E5", theme="E", title="Thick Brane Worlds and Their Stability",
         authors="S. Kobayashi, K. Koyama, J. Soda", year="2001",
         venue="Phys. Rev. D 65, 064014 (2002); arXiv:hep-th/0107025", url="https://arxiv.org/abs/hep-th/0107025",
         finding="Non-singular thick Poincare, de Sitter and AdS branes with a dilaton and potential; the effective potentials of the scalar-perturbation master equations are positive definite, so these systems are stable.",
         relevance="A counterpoint: smooth thick de Sitter walls with no thin shell are stable, whereas HDBLAST's thin shell with detuned tension has a tachyon. The master-variable method is a candidate for the +1 branch stability test being run in this round.",
         implication="method", access=S, queries=[14]),
    dict(id="E6", theme="E", title="Fake supergravity and domain wall stability",
         authors="D. Z. Freedman, C. Nunez, M. Schnabl, K. Skenderis", year="2004",
         venue="Phys. Rev. D 69, 104027", url="https://ui.adsabs.harvard.edu/abs/2004PhRvD..69j4027F/abstract",
         finding="A generalized Witten-Nester spinor argument proves stability of flat domain walls with no supersymmetry and in any dimension, and is extended to AdS-sliced walls (Janus is shown stable).",
         relevance="Covers HDBLAST's balanced flat wall (delta=0) but, per the snippet, only flat and AdS-sliced walls: no comparable positive-energy theorem is cited for de Sitter-sliced walls. That fits the registered de Sitter shell having a tachyon, and it means stability of the +1 branch must be computed directly.",
         implication="method", access=S, queries=[17]),
    dict(id="E7", theme="E", title="Hidden Supersymmetry of Domain Walls and Cosmologies",
         authors="K. Skenderis, P. K. Townsend", year="2006",
         venue="Phys. Rev. Lett. 96, 191301", url="https://www.osti.gov/etdeweb/biblio/20777232",
         finding="Every domain-wall solution of gravity plus scalars with Minkowski or AdS worldvolume admits Killing spinors and first-order equations with a solution-determined superpotential; by analytic continuation, flat or closed FLRW cosmologies obey similar equations via pseudo-Killing spinors.",
         relevance="A first-order (fake-superpotential) description of curved flows. HDBLAST's de Sitter-sliced static solutions need the curved or pseudo version; this is a possible route to an existence proof for the +1 branch.",
         implication="method", access=S, queries=[48]),
    dict(id="E8", theme="E", title="Coupled bulk and brane fields about a de Sitter brane",
         authors="A. Cardoso, K. Koyama, A. Mennim, S. S. Seahra, D. Wands", year="2006",
         venue="Phys. Rev. D 75, 084002 (2007); arXiv:hep-th/0612202", url="https://arxiv.org/abs/hep-th/0612202",
         finding="A bulk scalar in AdS linearly coupled to a scalar on a de Sitter brane has zero, one or two bound states plus continuum resonances, depending on the masses and coupling. A light radion with m = sqrt(2) H satisfies the two-brane boundary conditions but is not normalizable with a single brane. With test-field matter on the brane, this mode, the zero mode and an infinite ladder of discrete tachyonic modes become normalizable.",
         relevance="Directly relevant to HDBLAST's matter extension, which couples the brane field chi to the bulk phi. Adding brane fields can make tachyonic ladders normalizable, so a coupled-sector stability check is required before trusting any matter-driven trajectory.",
         implication="challenges", access=S, queries=[97, 92]),
    dict(id="E9", theme="E", title="Exactly solvable model for cosmological perturbations in dilatonic brane worlds",
         authors="K. Koyama, K. Takahashi", year="2003",
         venue="arXiv:hep-th/0307073 (also hep-th/0312087)", url="https://arxiv.org/pdf/hep-th/0307073",
         finding="A bulk scalar with an exponential potential and an exponential coupling to the brane tension gives power-law inflation on a single brane. The background with scalar backreaction and the perturbations obeying the junction conditions are solved exactly.",
         relevance="An exact benchmark for validating HDBLAST's 5D perturbation and evolution codes on a problem with a known answer, a cheap calibration control.",
         implication="method", access=S, queries=[38]),
    dict(id="E10", theme="E", title="Primordial Correlators from a Kaluza-Klein Graviton Continuum",
         authors="not captured in snippet", year="2026",
         venue="arXiv:2608.01762 (3 Aug 2026)", url="https://arxiv.org/abs/2608.01762",
         finding="A spectral representation for inflationary correlators mediated by a continuum of states, realized in an RS2-like braneworld with the inflaton on a de Sitter brane in AdS5. The tensor sector contains a localized zero mode and a KK graviton continuum with a gap of order H; the query-37 snippet puts the threshold at 3H/2, the principal-series edge.",
         relevance="HDBLAST's certified 'no scalar bound state below 9H^2/4' (Chat 10) uses exactly this threshold, (3H/2)^2. This paper shows how such a continuum could become an observable (cosmological-collider-like signals), if HDBLAST ever has an inflating stage with perturbations.",
         implication="method", access=S, queries=[41, 37]),
    dict(id="E11", theme="E", title="Complex scalar field thick branes: stability of linear perturbation and evolution of scalar Kaluza-Klein modes coupled with gravity",
         authors="not captured in snippet", year="2026",
         venue="arXiv:2609.21421 (18 Sept 2026)", url="https://arxiv.org/abs/2609.21421",
         finding="Minkowski, de Sitter and AdS thick branes from a complex scalar show no instability in the scalar and vector sectors. Factorizing the tensor equation excludes tachyonic tensor modes. The scalar zero mode is localized on Minkowski and de Sitter branes, with a gapless continuous scalar KK spectrum.",
         relevance="A current example of a sector-by-sector stability analysis of de Sitter branes, comparable in scope to HDBLAST Chat 12.",
         implication="method", access=S, queries=[92, 49]),
    dict(id="E12", theme="E", title="BRANECODE: A Program for Simulations of Braneworld Dynamics",
         authors="J. Martin, G. Felder, A. Frolov, M. Peloso, L. Kofman (per query; snippet names 'the authors you mentioned')", year="2004",
         venue="arXiv:hep-ph/0404141; companion paper 'Brane world dynamics with the BraneCode', arXiv:hep-th/0309001 (also in the query-88 results)", url="https://arxiv.org/abs/hep-ph/0404141v1",
         finding="A C++ code for fully nonlinear evolution of 5D braneworlds with bulk scalar fields, described as the first of its type; it was used to confirm the tachyonic instability of 'stabilized' de Sitter branes (item E3).",
         relevance="Prior numerical art for HDBLAST's rolloff5d evolutions. Reproducing a published BraneCode test case would calibrate HDBLAST's solver externally.",
         implication="method", access=S, queries=[88, 18]),
    # ---------------- F. Einstein-scalar dS-sliced flows (Kiritsis-Nitti programme) and holographic reheating ----------------
    dict(id="F1", theme="F", title="Holographic RG flows on curved manifolds and quantum phase transitions",
         authors="J. K. Ghosh, E. Kiritsis, F. Nitti, L. T. Witkowski", year="2017",
         venue="JHEP 05 (2018) 034; arXiv:1711.08462", url="https://arxiv.org/abs/1711.08462",
         finding="Einstein-dilaton flows with dS_d, AdS_d or S^d slicing and a general potential: UV and IR asymptotics, new flows at finite curvature with no flat counterpart, and bouncing flows that persist at finite curvature.",
         relevance="A classification framework for HDBLAST's static de Sitter-sliced solutions. The +1 branch, whose cone sits near phi=+1, may be one of the finite-curvature flows with no flat counterpart.",
         implication="method", access=S, queries=[73]),
    dict(id="F2", theme="F", title="De Sitter and Anti-de Sitter branes in self-tuning models",
         authors="J. K. Ghosh, E. Kiritsis, F. Nitti, L. T. Witkowski", year="2018",
         venue="JHEP 11 (2018) 128; arXiv:1807.09794", url="https://arxiv.org/abs/1807.09794",
         finding="Maximally symmetric curved-brane solutions in dilatonic self-tuning braneworlds: no de Sitter or AdS brane vacua exist unless the near-boundary asymptotics are modified, after which curved solutions with a stabilized brane position generically exist.",
         relevance="The closest published model class: a brane with scalar-dependent tension in an Einstein-dilaton bulk with de Sitter solutions. HDBLAST's bulk is compact (regular cone, no UV boundary), so the existence obstruction differs, but the matching-condition machinery carries over.",
         implication="method", access=S, queries=[72]),
    dict(id="F3", theme="F", title="de Sitter versus Anti de Sitter flows and the (super)gravity landscape (and Part II)",
         authors="E. Kiritsis, C. Tsouros (Part I); Part II authors per snippet: Kiritsis, Morales-Tejera, Rosen", year="2019",
         venue="arXiv:1901.04546 (JHEP 08 (2023) 126 per listing); Part II arXiv:2510.12373, JHEP 04 (2026) 111", url="https://arxiv.org/abs/1901.04546",
         finding="Part I extends the classification of regular Einstein-scalar solutions to the de Sitter regime, including cosmic clocks that reverse direction without a curvature singularity, and finds no regular solutions interpolating between de Sitter and AdS extrema for generic potentials. Part II finds no regular ('Centaur') solutions interpolating between an AdS boundary and a de Sitter interior for d>2, even with several scalars and a nontrivial field-space metric.",
         relevance="Constrains any HDBLAST variant in which a positive-energy 5D region, the 'blast', is joined smoothly to the AdS bulk. Such a junction would need a shell or a singularity, not a smooth scalar flow.",
         implication="constrains", access=S, queries=[69, 75],
         caveat="Journal attribution of Part I and author list of Part II come from search listings and were not cross-checked."),
    dict(id="F4", theme="F", title="Holographic confining theories on space-times with constant positive curvature",
         authors="J. Kastikainen, E. Kiritsis, F. Nitti", year="2025",
         venue="JHEP 09 (2025) 139; arXiv:2502.04036", url="https://arxiv.org/abs/2502.04036",
         finding="Two branches of solutions compete, with a phase transition as the curvature varies: the low-curvature phase has the flat-space IR geometry, the high-curvature phase a regular interior; the transition is first- or higher-order depending on the potential's leading exponent.",
         relevance="HDBLAST also has two static branches (cone near -1 and near +1). The same free-energy (on-shell action) comparison would say which is preferred at the registered H, a cheap, well-defined next calculation.",
         implication="method", access=S, queries=[77]),
    dict(id="F5", theme="F", title="Holographic self-tuning of the cosmological constant; Brane cosmology and the self-tuning of the cosmological constant",
         authors="C. Charmousis, E. Kiritsis, F. Nitti (2017); A. Amariti, C. Charmousis, D. Forcella, E. Kiritsis, F. Nitti (2019)", year="2017",
         venue="JHEP 09 (2017) 031, arXiv:1704.05075; JCAP 10 (2019) 007, arXiv:1904.02727; bulk-black-hole version arXiv:2003.05767", url="https://arxiv.org/abs/1704.05075",
         finding="A Standard Model brane separates an infinite-volume UV region from a finite-volume IR region in an Einstein-scalar bulk; for generic brane vacuum energy, regular flat-brane solutions exist. The cosmology of such branes, including matching conditions in several coordinate systems and bulk black holes, is worked out in the follow-ups.",
         relevance="The time-dependent PDE-plus-junction problem is the same type as HDBLAST's roll-off; its coordinate choices and solution strategies are directly reusable.",
         implication="method", access=S, queries=[74, 78]),
    dict(id="F6", theme="F", title="A dynamical inflaton coupled to strongly interacting matter",
         authors="C. Ecker, E. Kiritsis, W. van der Schee", year="2023",
         venue="Phys. Rev. Lett. 130, 251001; arXiv:2302.06618", url="https://arxiv.org/abs/2302.06618",
         finding="Self-consistently couples the Einstein-inflaton equations to a strongly coupled QFT described holographically, and finds inflation, a reheating phase, and finally a universe dominated by the QFT in thermal equilibrium.",
         relevance="A controlled demonstration of reheating into a hot (holographic) sector, the step HDBLAST has not achieved. It suggests treating part of the 5D bulk as the hot sector's dual.",
         implication="supports", access=S, queries=[84, 81]),
    dict(id="F7", theme="F", title="Gravitational reheating at strong coupling",
         authors="A. Buchel", year="2023",
         venue="JHEP 07 (2023) 159; arXiv:2304.11195", url="https://arxiv.org/abs/2304.11195",
         finding="Uses gauge/gravity duality to estimate the maximal reheating temperature of strongly coupled theories after a rapid exit from de Sitter; reheating is most efficient when H is much larger than the conformal-breaking scale and the breaking operators are nearly marginal.",
         relevance="HDBLAST's shell moves between de Sitter rates (H/H0 falling from about 0.64 to 0.607). A bound of this type could say how much gravitational particle production such a mild change can give, probably very little.",
         implication="method", access=S, queries=[86]),
    dict(id="F8", theme="F", title="Self-sustained, out-of-equilibrium inflation",
         authors="J. Casalderrey-Solana and colleagues (snippet)", year="2025",
         venue="arXiv:2512.18079", url="https://arxiv.org/abs/2512.18079",
         finding="Holographic de Sitter-invariant states of non-conformal strongly coupled QFTs on dS4: out-of-equilibrium effects can sustain exponential inflation with H far below the QFT scale and the species scale; fine-tuning scales only logarithmically; apparent horizons with growing area signal growing comoving entropy; the regime can be the late-time limit of an FRW start.",
         relevance="A de Sitter attractor with a coupled hot sector. It contrasts with HDBLAST's attractor, an empty RS de Sitter brane, and suggests one way a coupled matter sector could change the endpoint.",
         implication="context", access=S, queries=[80, 81]),
    dict(id="F9", theme="F", title="Brane Cosmology from AdS/BCFT",
         authors="Fujiki, Kanda, Kohara, Takayanagi (surnames only, per snippet)", year="2025",
         venue="JHEP 03 (2025) 135; arXiv:2501.05036", url="https://arxiv.org/abs/2501.05036",
         finding="An end-of-the-world brane in AdS with a brane-localized scalar: the brane equation becomes a Friedmann-like equation, the model can describe creating a universe via a big bang, the near-hyperplane effective action is Liouville gravity with scalar matter, and a timelike g-theorem is proven from the null energy condition (AdS3/BCFT2).",
         relevance="A recent formal analogue of a shell carrying a scalar in AdS that produces a big-bang-like creation; the null-energy-condition monotonicity is a structural tool HDBLAST could test on its shell trajectories.",
         implication="method", access=S, queries=[29]),
    dict(id="F10", theme="F", title="Effective Dynamics of Inflationary End-of-the-World Branes in AdS3",
         authors="K. Fujiki and others (snippet)", year="2026",
         venue="arXiv:2609.11643 (Sept 2026)", url="https://arxiv.org/abs/2609.11643",
         finding="Integrates out the bulk to obtain a Liouville-like effective theory for a 2D cosmological EOW brane with a localized scalar; constructs slow-roll inflating trajectories, regular Euclidean geometries continuing to Lorentzian de Sitter, and the semiclassical on-shell action.",
         relevance="A method for deriving a brane-scalar effective action and a Euclidean continuation in a lower-dimensional toy model, comparable to HDBLAST's closed-form 4D effective theory (Chat 9).",
         implication="method", access=S, queries=[30]),
    dict(id="F11", theme="F", title="Cosmology at the end of the world; Cosmology from the vacuum; Accelerating cosmology from a holographic wormhole",
         authors="S. Antonini, B. Swingle (2020); S. Antonini, P. Simidzija, B. Swingle, M. Van Raamsdonk (2022-2024)", year="2020",
         venue="Nature Phys. 16 (2020); arXiv:2203.11220 (CQG 41, 2024); Phys. Rev. Lett. 130, 221601 (2023)", url="https://www.nature.com/articles/s41567-020-0909-6",
         finding="Cosmologies on end-of-the-world branes moving in charged AdS black-hole spacetimes, realized microscopically in AdS/CFT, and follow-ups obtaining cosmology, including accelerating cosmology, from holographic constructions.",
         relevance="Microscopic (holographic) control of brane cosmologies inside AdS black holes: a possible long-term UV framing for a shell-plus-bulk-black-hole version of HDBLAST.",
         implication="context", access=S, queries=[27]),
    # ---------------- G. Swampland and string-theory context ----------------
    dict(id="G1", theme="G", title="De Sitter Space and the Swampland",
         authors="G. Obied, H. Ooguri, L. Spodyneiko, C. Vafa", year="2018", caveat="Year from general knowledge; not stated in the snippet.",
         venue="arXiv (2018)", url="https://www.semanticscholar.org/paper/De-Sitter-Space-and-the-Swampland-Obied-Ooguri/599c99078a502b7d462d0b8783ff4a2c4436dc19",
         finding="Conjectures that |grad V| >= c V for the scalar potential of any consistent quantum-gravity theory, which forbids de Sitter vacua.",
         relevance="HDBLAST's late-time attractor is an empty de Sitter brane. If the model were embedded in string theory, it would be judged against this family of conjectures; brane-induced de Sitter (dark bubble) is argued to evade them, and HDBLAST's version has not been assessed.",
         implication="constrains", access=S, queries=[21]),
    dict(id="G2", theme="G", title="de Sitter Bubbles and the Swampland",
         authors="A. Bedroya, M. Montero, C. Vafa, I. Valenzuela", year="2020",
         venue="arXiv:2008.07555", url="https://arxiv.org/abs/2008.07555",
         finding="Effective theories of rolling scalars dual to a cascade of short-lived de Sitter spaces decaying by bubble nucleation; the trans-Planckian censorship conjecture (TCC) essentially incorporates the weak gravity and distance conjecture constraints on the dual potentials.",
         relevance="TCC-type bounds would limit how long any HDBLAST de Sitter phase (the static shell or the +1 plateau) can last in a UV-complete version.",
         implication="constrains", access=S, queries=[46]),
    dict(id="G3", theme="G", title="Lectures on the string landscape and the Swampland",
         authors="N. B. Agmon, A. Bedroya, M. J. Kang, C. Vafa", year="2022",
         venue="arXiv:2212.06187", url="https://arxiv.org/pdf/2212.06187",
         finding="Lecture notes on the string landscape and on the Swampland programme's constraints for EFTs with a quantum-gravity UV completion.",
         relevance="Background reference for the swampland criteria cited here.",
         implication="context", access=S, queries=[54]),
    dict(id="G4", theme="G", title="On the Origin and Fate of Our Universe",
         authors="C. Vafa", year="2025",
         venue="Gen. Relativ. Gravit. (2025); arXiv:2501.00966", url="https://arxiv.org/abs/2501.00966",
         finding="A short review of swampland bounds on positive potentials, the de Sitter conjecture, TCC and its relation to the species scale, with implications for inflation and the fate of the universe.",
         relevance="The current mainstream quantum-gravity view on origins: any HDBLAST claim about an inflating or de Sitter origin should be stated against it.",
         implication="constrains", access=S, queries=[56]),
    dict(id="G5", theme="G", title="The dark dimension scenario (Montero, Vafa, Valenzuela 2022; popular account)",
         authors="M. Montero, C. Vafa, I. Valenzuela (per snippet; arXiv:2205.12293 named in snippet, not opened)", year="2022",
         venue="Quanta Magazine article (2024) and follow-up EPJC paper arXiv:2309.09330", url="https://www.quantamagazine.org/in-a-dark-dimension-physicists-search-for-missing-matter-20240201/",
         finding="One micron-size extra dimension with a Kaluza-Klein scale of order meV, motivated by the tiny cosmological constant (about 1e-122 in Planck units) and swampland arguments.",
         relevance="A concrete single-extra-dimension scenario with laboratory tests; A12 ties the dark bubble to it. HDBLAST's extra-dimension scale (AdS radius ell = 9 in model units at phi=+1) has no physical normalization yet (open item 7).",
         implication="context", access=S, queries=[22]),
    dict(id="G6", theme="G", title="Inflation with a Growing Fifth Dimension",
         authors="Harvard group (snippet gives affiliation only)", year="2025",
         venue="JHEP 05 (2026) 169; arXiv:2512.04177", url="https://arxiv.org/abs/2512.04177",
         finding="Inflation with a finite initial time in warped AdS5 with UV and IR branes. The inflaton potential detunes the brane tension, so the fifth dimension grows: a two-field (inflaton plus radion) hyperbolic model with early radion fast-roll and late inflaton slow-roll. The earliest modes are radion-sourced and give a suppressed, blue-tilted scalar spectrum and oscillatory tensors, in principle visible in the CMB. The model links to the dark dimension.",
         relevance="Structurally the closest 2025-2026 match to HDBLAST's core mechanism: a detuned brane tension drives the dynamics of the extra dimension. It shows how such a mechanism yields observables (large-scale suppression), and is a template for HDBLAST open item 5.",
         implication="supports", access=S, queries=[85]),
    dict(id="G7", theme="G", title="De Sitter space constraints on brane tensions and couplings",
         authors="S. Hassan, G. Obied, J. March-Russell", year="2024",
         venue="arXiv:2411.14529", url="https://arxiv.org/abs/2411.14529",
         finding="Festina-Lente-type arguments using Nariai de Sitter black holes bound p-brane tensions in de Sitter by the Hubble rate and by Chern-Simons-like worldvolume couplings; D-branes satisfy them; axion domain walls evade them.",
         relevance="Tangential: HDBLAST's shell has no gauge couplings, so these bounds would matter only if gauge fields were added on the shell.",
         implication="context", access=S, queries=[44]),
    dict(id="G8", theme="G", title="Stability of non-supersymmetric vacua from calibrations",
         authors="not captured in snippet", year="2025",
         venue="JHEP 11 (2025) 070; arXiv:2507.02787", url="https://arxiv.org/abs/2507.02787",
         finding="Calibrations bound D-brane energies and forbid, in the probe approximation, nucleation of D-brane bubbles in several type II AdS4 and AdS5 non-supersymmetric vacua, many of which resisted all decay channels tested. Query 23 snippets summarise the opposite view: the Ooguri-Vafa conjecture that non-SUSY AdS is at best metastable via Brown-Teitelboim brane nucleation.",
         relevance="The instability of non-supersymmetric AdS, which the dark-bubble origin mechanism needs, is contested. HDBLAST's bulk vacua come from a real superpotential and are perturbatively stable; whether a 5D 'blast' event is available depends on that unresolved UV question.",
         implication="context", access=S, queries=[70, 23]),
    dict(id="G9", theme="G", title="Dark energy from string theory: an introductory review",
         authors="D. Andriot", year="2026",
         venue="arXiv:2603.25797 (Mar 2026, rev. Apr 2026)", url="https://arxiv.org/abs/2603.25797",
         finding="A review of obtaining dark energy from string theory, either as a cosmological constant (de Sitter solution) or dynamical (quintessence), including historical no-go constraints and attempts to evade them.",
         relevance="The current reference point for whether any late-time de Sitter phase, such as HDBLAST's +1 plateau, can be UV-complete.",
         implication="context", access=S, queries=[104]),
    dict(id="G10", theme="G", title="Our universe: An expanding bubble in an extra dimension (press release on A1)",
         authors="Uppsala University press release via ScienceDaily", year="2018",
         venue="ScienceDaily, 28 Dec 2018", url="https://www.sciencedaily.com/releases/2018/12/181228164824.htm",
         finding="Popular account of the 2018 dark bubble proposal: the universe rides an expanding bubble where two five-dimensional spaces meet. A 2026 search found no newer comparable press story.",
         relevance="Shows that 'our universe is a 5D bubble' has already been widely publicised; HDBLAST communication should cite this line to avoid implying the concept is new.",
         implication="context", access=S, queries=[67]),
]

EXCLUDED = [
    dict(query=60, reason="'What's the (Dark) Matter with Cosmological Bubbles?' is about 4D first-order phase transitions; off-topic."),
    dict(query=79, reason="'Scalar stars and lumps with (A)dS core' concerns 4D compact objects; only indirectly relevant, covered by B9."),
    dict(query=108, reason="No web-indexed item mentions HDBLAST or Ricardo Maldonado; the query surfaced C16 and standard ekpyrotic items."),
    dict(query=63, reason="Double-holography / Karch-Randall information-theory papers (e.g. arXiv:2504.21856) surfaced; judged not relevant to the HDBLAST dynamics question."),
    dict(query=25, reason="Popular articles on 'universe from a 4D-bulk black hole' and dark-dimension primordial black holes (arXiv:2506.14874); popular framing of B7, not new physics."),
]
