#!/usr/bin/env python3
"""Referee (math) - independent extra checks for the VECTOR sector and the SPECIAL harmonics.
VECTOR
 X1  general gauge (Bv and Fv both present): the bulk equations depend only on sigma_V = Bv - rho^2 Fv':
       EQ_{x1x2} = (E'T/2)(sigma' + 2H sigma),  EQ_{tau x2} = (E(T'-2T)/2)(sigma' + 2H sigma),  EQ_{y x2} = -(sigma/(2rho^2)) [(Box+3)V]_x2 .
 X2  Z2-shell junction (pure tension, delta phi = 0):  delta(K_{mu nu} - (sigma_t/6) g_{mu nu}) = -sigma_V * nabla_(mu V_nu)  at the shell
     (K_{mu nu} = -Gamma^y_{mu nu} of the perturbed metric; background junction rho'/rho = sigma_t/6).
     => sigma_V(y_b) = 0, hence C = 0 in sigma_V = C/rho^2 WITHOUT any appeal to cone regularity.
 X3  overlap with the tensor sector: for transverse V with (Box+3)V = 0, S = nabla_(mu V_nu) is TT (divergence = (Box+3)V/2).
SPECIAL HARMONICS (Y = e^tau x1, Hess Y = -gamma Y), NO gauge fixing beyond nothing at all:
 X4  general perturbation  g_yy = 1+2 xi Y, g_{y mu} = Bs d_mu Y, g_{mu nu} = rho^2(1+2 psi Y) gamma, phi = phi0 + chi Y.
     Put a := chi/phi0', b := H a - psi (always possible since phi0' != 0): the pure-gauge part generated by (a,b) carries ALL of psi, chi.
     Remainder: xi_r = xi - a', Bs_r = Bs - a - rho^2 b', psi_r = chi_r = 0.  Check: the field equations for the remainder are
        EQ_{y mu} = 3 H xi_r d_mu Y + (...)Bs_r  etc.;  we solve them and show they force a relation leaving only pure gauge.
 X5  injectivity: psi_g = 0 together with the residual-gauge ODE implies phi0'^2 b = 0.
 X6  consistency with the generic scalar certificate at mu2 = -4: the longitudinal-gauge pure-gauge mode has chi_g = phi0' a, and the generic
     shell mismatch  chi' + 2 phi0' psi + (s2/2) chi  evaluated on it equals  phi0' B a + (terms that vanish by the gauge ODE)."""
import json, sys, time
import sympy as sp
from lin_gr import *
t0 = time.time(); res = {}
def record(n, ok, note=""): res[n] = dict(passed=bool(ok), note=note); print("[%s] %s %s" % ("PASS" if ok else "FAIL", n, note), flush=True)
xs = X[1:]; gi4 = gam.inv(); H = rp/rho
red = lambda e: sp.simplify(bg_reduce(e))
# ---------------- VECTOR ----------------
Bv, Fv = sp.Function('Bv')(y), sp.Function('Fv')(y)
T = sp.Function('T')(tau); E = sp.Function('E')(x1)
Vlow = [0, 0, T*E, 0]
DV = sp.Matrix(4, 4, lambda m, n_: sp.diff(Vlow[n_], xs[m]) - sum(chr4(l, m, n_)*Vlow[l] for l in range(4)))
S2 = DV + DV.T                                                        # 2 nabla_(mu V_nu)
dg = sp.zeros(5, 5); dg[0, 3] = dg[3, 0] = Bv*T*E
for m in range(4):
    for n_ in range(4): dg[m+1, n_+1] = rho**2*Fv*S2[m, n_]
eq = first_order_equations(dg)
sig = Bv - rho**2*sp.diff(Fv, y); C1 = sp.diff(sig, y) + 2*sp.diff(rho, y)/rho*sig
def cov_d2(Tm): return [[[sp.diff(Tm[m, n_], xs[l]) - sum(chr4(s, l, m)*Tm[s, n_] + chr4(s, l, n_)*Tm[m, s] for s in range(4)) for n_ in range(4)] for m in range(4)] for l in range(4)]
DS = cov_d2(S2); op = [sp.simplify(sum(gi4[l, l]*DS[l][l][n_] for l in range(4))) for n_ in range(4)]      # (Box+3)V
# NOTE: for Fv != 0 the (mu nu) equations also contain Fv * (4D Lichnerowicz of S): use the general formula  -(F/2)(Box-2)(S2) + F*sym nabla(div S2)
D3 = [[[[sp.diff(DS[l][m][n_], xs[kk]) - sum(chr4(s, kk, l)*DS[s][m][n_] + chr4(s, kk, m)*DS[l][s][n_] + chr4(s, kk, n_)*DS[l][m][s] for s in range(4)) for n_ in range(4)] for m in range(4)] for l in range(4)] for kk in range(4)]
BoxS = sp.Matrix(4, 4, lambda m, n_: sum(gi4[l, l]*D3[l][l][m][n_] for l in range(4)))
cdop = sp.Matrix(4, 4, lambda m, n_: sp.diff(op[n_], xs[m]) - sum(chr4(s, m, n_)*op[s] for s in range(4)))
symop = (cdop + cdop.T)/2
# covariant form of V2a: EQ_{mu nu}|_{Fv=0} = -(1/2)(Bv' + 2H Bv) S2_{mu nu} ?  test both signs, general gauge, including the Lichnerowicz remainder
def munu_target(sgn):
    return sp.Matrix(4, 4, lambda m, n_: sgn*sp.Rational(1, 2)*C1*S2[m, n_] - (Fv/2)*(BoxS[m, n_] - 2*S2[m, n_]) + Fv*symop[m, n_])
signs = [sg for sg in (1, -1) if all(red(eq[(m+1, n_+1)] - munu_target(sg)[m, n_]) == 0 for m in range(4) for n_ in range(m, 4))]
record("X1a_EQ_munu_general_gauge_=_s*(1/2)(sigma'+2H sigma)*2nabla_(mu V_nu)_+_Fv*[4D_terms_prop_to_(Box+3)V]", len(signs) == 1, "s = %s" % signs)
# the Fv 4D terms vanish identically? (they must combine into derivatives of (Box+3)V): check  -(1/2)(Box-2)S2 + sym nabla op = 0 when op = 0 is NOT assumed:
lich = sp.Matrix(4, 4, lambda m, n_: sp.simplify(-(BoxS[m, n_] - 2*S2[m, n_])/2 + symop[m, n_]))
record("X1b_identity_(Box-2)[2nabla_(mu V_nu)]_=_2nabla_(mu[(Box+3)V]_nu)_(so_Fv_drops_out_of_EQ_munu:_only_sigma_V_appears)", all(lich[m, n_] == 0 for m in range(4) for n_ in range(4)))
record("X1c_EQ_ynu_=_-(sigma_V/(2rho^2))[(Box+3)V]_nu_in_general_gauge", all(red(eq[(0, n_+1)] + sig/(2*rho**2)*op[n_]) == 0 for n_ in range(4)) and red(eq[(0, 0)]) == 0)
# X2 junction
g0 = background_metric(); g = g0 + eps*dg; g0i = g0.inv(); gi = (g0i - eps*g0i*dg*g0i)
def Gam_y(m, n_):   # Gamma^y_{mu nu} of the perturbed metric, first order
    return lin(sum(gi[0, D]*(sp.diff(g[D, m+1], X[n_+1]) + sp.diff(g[D, n_+1], X[m+1]) - sp.diff(g[m+1, n_+1], X[D])) for D in range(5))/2)
sigt = sp.symbols('sigma_t')
okJ = True
for m in range(4):
    for n_ in range(m, 4):
        Kmn = lin(-Gam_y(m, n_))               # K_{mu nu} = nabla_mu n_nu = -Gamma^y_{mu nu}, n_A = (1,0,0,0) (unit to first order since delta g_yy = 0)
        okJ &= sp.simplify(Kmn.coeff(eps, 0) - rho*sp.diff(rho, y)*gam[m, n_]) == 0   # background K = rho rho' gamma
        junction = lin(Kmn - sigt/6*g[m+1, n_+1]).coeff(eps, 1).subs(sigt, 6*sp.diff(rho, y)/rho)
        okJ &= sp.simplify(junction + sig*S2[m, n_]/2) == 0
record("X2_junction_delta(K_munu-(sigma_t/6)g_munu)_=_-sigma_V*nabla_(mu V_nu)_=>_sigma_V(y_b)=0_=>_C=0", okJ)
divS = [sp.simplify(sum(gi4[l, l]*DS[l][l][n_] for l in range(4)) - op[n_]) for n_ in range(4)]
trS = sp.simplify(sum(gi4[m, m]*S2[m, m] for m in range(4)))
record("X3_nabla_(mu V_nu)_is_traceless_with_divergence_(Box+3)V/2_(TT_iff_(Box+3)V=0:_overlap_with_m2=0_tensor)", trS == 0 and all(d == 0 for d in divS))
# ---------------- SPECIAL ----------------
Yf = sp.exp(tau)*x1
xi, Bs, psi, chi = [sp.Function(n)(y) for n in ('xi', 'Bs', 'psi', 'chi')]
def pert(xi_, Bs_, psi_):
    d = sp.zeros(5, 5); d[0, 0] = 2*xi_*Yf
    for m in range(4):
        d[0, m+1] = d[m+1, 0] = Bs_*sp.diff(Yf, xs[m])
        d[m+1, m+1] = 2*rho**2*psi_*Yf*gam[m, m]
    return d
# remainder perturbation (psi = chi = 0)
eqr = first_order_equations(pert(xi, Bs, 0), 0)
comp = {k_: sp.factor(red(v)) for k_, v in eqr.items()}
nz = {k_: v for k_, v in comp.items() if v != 0}
for k_, v in nz.items(): print("   remainder EQ", k_, "=", v)
# Expect EQ_{y mu} = d_mu Y * 3H xi_r (+ Bs-terms); read off the y-mu equation and the yy equation, solve for xi_r, Bs_r
e_ymu = sp.simplify(comp[(0, 2)]/sp.diff(Yf, xs[1]))
e_yy = sp.simplify(comp[(0, 0)]/Yf)
e_tt = sp.simplify(comp[(1, 1)]/(Yf*gam[0, 0]))
print("   (y mu):", e_ymu); print("   (yy):", e_yy); print("   (mu nu)/gamma:", e_tt)
sol_xi = sp.solve(e_ymu, xi)
record("X4a_remainder_(y_mu)_equation_is_algebraic_in_xi_r", len(sol_xi) == 1, "xi_r = %s" % (sol_xi[0] if sol_xi else None))
if sol_xi:
    sub = {xi: sol_xi[0]}
    e2 = sp.simplify(bg_reduce(e_yy.subs(sub).doit())); e3 = sp.simplify(bg_reduce(e_tt.subs(sub).doit()))
    print("   after xi_r eliminated: (yy) ->", sp.factor(e2)); print("   (mu nu) ->", sp.factor(e3))
    res["X4_info"] = dict(passed=True, note="yy: %s ; munu: %s" % (sp.factor(e2), sp.factor(e3)))
    # linear combination:  -(3 rho' rho^3/2)*(yy) ... : show the two surviving equations are  c1*Bs = 0, c2*Bs = 0 with  (suitable combination) = 3 phi0'^2 Bs
    c_yy = sp.simplify(e2/Bs*(-3*rp*rho**3/2)); c_mn = sp.simplify(e3/Bs*(-3*rp*rho))
    comb = sp.simplify(2*c_mn - c_yy)
    record("X4b_remainder_equations_reduce_to_c1*Bs_r=0,_c2*Bs_r=0_with_2*c2-c1=3*rho^2*phi0'^2_=>_Bs_r=0,_xi_r=0_(bulk_solution_==_Lie_derivative,_no_gauge_fixing)",
           sp.simplify(comb - 3*rho**2*pp**2) == 0 and not c_yy.has(Bs) and not c_mn.has(Bs), "c1 = %s, c2 = %s" % (sp.factor(c_yy), sp.factor(c_mn)))
# X5 injectivity
b = sp.Function('b')(y); Hf = sp.diff(rho, y)/rho
b1 = -b/(rho*sp.diff(rho, y))                                        # psi_g = H a - b = 0 with a = -rho^2 b'
ode = rho**2*sp.diff(b1, y) + 4*rho*sp.diff(rho, y)*b1 + 2*b
ode = ode.subs(sp.diff(b, y), b1)
r2 = (sp.diff(rho, y)**2/rho - 1/rho - rho*sp.diff(ph0, y)**2/3)
ode = sp.simplify(ode.subs(sp.diff(rho, y, 2), r2))
record("X5_psi_g=0_and_gauge_ODE_imply_-rho^2 phi0'^2 b/(3 rho'^2)=0_(injective_when_phi0'!=0,_rho'!=0)", sp.simplify(ode + rho**2*sp.diff(ph0, y)**2*b/(3*sp.diff(rho, y)**2)) == 0)
# X6 generic shell mismatch on the longitudinal pure-gauge mode at mu2 = -4
s2 = sp.symbols('sigma2')
a_ = -rho**2*sp.diff(b, y); psi_g = Hf*a_ - b; chi_g = sp.diff(ph0, y)*a_
mism = sp.diff(chi_g, y) + 2*sp.diff(ph0, y)*psi_g + s2/2*chi_g
b2 = -(4*rho*sp.diff(rho, y)*sp.diff(b, y) + 2*b)/rho**2
mism = mism.subs(sp.diff(b, y, 2), b2)
Bq = sp.diff(ph0, y, 2)/sp.diff(ph0, y) + s2/2
record("X6_generic_shell_mismatch_on_gauge_mode_at_mu2=-4_equals_phi0'*B*a_(same_obstruction_as_S3b)", sp.simplify(mism - sp.diff(ph0, y)*Bq*a_) == 0)
ok = all(v["passed"] for v in res.values())
json.dump(dict(sympy=sp.__version__, all_pass=ok, checks=res, seconds=time.time()-t0), open("VECTOR_SPECIAL_EXTRA_RESULT.json", "w"), indent=1)
print("ALL PASS" if ok else "SOME CHECKS FAILED"); sys.exit(0 if ok else 1)
