"""Mechanism screen, part 1: what the archived 5D roll-off already says.

Reads the unchanged Chat14 archive (copied inside the 22 Sept checkpoint) and, along
each registered-detuning shell trajectory, evaluates the exact shell identity
  H^2 = sigma^2/36 + v^2/12 - sigma'^2/48 + U/6 + Wy          (rho = p = j = 0)
to extract the Weyl ("dark radiation") scalar Wy = -E_tautau/3 generated by the blast,
tests the Weyl transport identity
  dWy/dtau + 4 H Wy = (1/6)[4 k_s w v - 4 H v^2 - v vdot + w wdot - U' v],
  k_s = sigma/6, w = -sigma'/2,
on the saved data, and records: Wy a^4, Omega_W = Wy/H^2, the shell tension budget
(sign of d sigma/dtau = sigma' v, i.e. energy flowing shell->bulk or bulk->shell) and the
effective equation of state of the collapse branch (ekpyrotic test w_eff >> 1 ?).
No evolution is rerun. Units: everything scaled by the initial H0 = 1/rho_b.
"""
import io, json, zipfile
import numpy as np
from common import *

RUNS = ['v2_t1e3_plus_c4', 'v2_t1e3_plus_c4_fine', 'v2_t1e3_plus_c4_finecoarse', 'v2_t1e3_plus_c4_ext',
        'v2_t1e3_minus_c4', 'v2_t1e3_minus_c4_fine', 'v2_t1e3_minus_c4_finecoarse']

def deriv(x, y):
    return np.gradient(y, x, edge_order=2)

def analyse(rec, summ):
    t_det = summ['t_det']; rb = summ['rho_b']
    s = rec[:, 9]; phi = rec[:, 1]; h = rec[:, 2]; vh = rec[:, 5]
    keep = np.concatenate(([True], np.diff(s) > 1e-12))      # strictly increasing proper time
    s, phi, h, vh, t = s[keep], phi[keep], h[keep], vh[keep], rec[keep, 0]
    sig = sigma(phi, t_det); s1 = sigma1(phi, t_det)
    # hatted: divide by H0^n, H0 = 1/rb
    Wy = h*h - vh*vh/12 - rb*rb*(sig*sig/36 - s1*s1/48 + U(phi)/6)
    Wy_wrong = h*h - vh*vh/12 - rb*rb*(sig*sig/36 + U(phi)/6)          # control: drop sigma'^2/48
    lna = np.concatenate(([0.], np.cumsum(0.5*(h[1:]+h[:-1])*np.diff(s))))
    # Weyl transport identity residual
    k = rb*sig/6; w = -rb*s1/2; vdot = deriv(s, vh); wdot = -rb*(4*phi)*vh/2
    rhs = (4*k*w*vh - 4*h*vh*vh - vh*vdot + w*wdot - rb**2*Up(phi)*vh)/6
    lhs = deriv(s, Wy) + 4*h*Wy
    scale = (np.abs(4*k*w*vh) + np.abs(rb**2*Up(phi)*vh) + np.abs(4*h*vh*vh) + np.abs(vh*vdot) + np.abs(w*wdot))/6 + 1e-300
    # control: identity with wrong factor (4H -> 3H)
    lhs_wrong = deriv(s, Wy) + 3*h*Wy
    inner = slice(3, -3)
    res = np.abs(lhs-rhs)[inner]; resw = np.abs(lhs_wrong-rhs)[inner]
    dsig = s1*vh                     # d sigma / d(H0 tau) in units of ... (sigma per H0 time)
    out = dict(
        n_samples=int(len(s)), H0_tau_end=float(s[-1]), phi_b_end=float(phi[-1]), H_over_H0_end=float(h[-1]),
        Wy_over_H0sq_initial=float(Wy[0]), Wy_over_H0sq_end=float(Wy[-1]),
        Wy_over_H0sq_max=float(Wy.max()), Wy_over_H0sq_min=float(Wy.min()),
        s_at_Wy_max=float(s[np.argmax(Wy)]), s_at_Wy_min=float(s[np.argmin(Wy)]),
        Omega_W_end=float(Wy[-1]/h[-1]**2) if abs(h[-1]) > 1e-12 else None,
        scalar_kinetic_fraction_end=float(vh[-1]**2/12/h[-1]**2) if abs(h[-1]) > 1e-12 else None,
        ln_a_end=float(lna[-1]),
        Wy_a4_over_H0sq=[float(x) for x in (Wy*np.exp(4*lna))[::max(1, len(s)//40)]],
        s_sample=[float(x) for x in s[::max(1, len(s)//40)]],
        Wy_sample=[float(x) for x in Wy[::max(1, len(s)//40)]],
        control_Wy_initial_without_sigma1_term=float(Wy_wrong[0]),
        weyl_identity_median_rel_residual=float(np.median(res/scale[inner])),
        weyl_identity_p95_rel_residual=float(np.percentile(res/scale[inner], 95)),
        weyl_identity_wrongfactor_median_rel_residual=float(np.median(resw/scale[inner])),
        sigma_initial=float(sig[0]), sigma_end=float(sig[-1]), sigma_max=float(sig.max()), sigma_min=float(sig.min()),
        tension_increase_total=float(np.sum(np.clip(np.diff(sig), 0, None))),
        tension_decrease_total=float(-np.sum(np.clip(np.diff(sig), None, 0))),
    )
    # collapse branch: effective equation of state while contracting
    contracting = h < -0.5
    if contracting.sum() > 5:
        eps = -deriv(s, h)/h**2
        idx = np.where(contracting)[0]
        sel = idx[(h[idx] > -30)]
        out['collapse'] = dict(
            weff_median_for_H_between_m0p5_and_m30=float(np.median(2*eps[sel]/3-1)),
            weff_range=[float(np.min(2*eps[sel]/3-1)), float(np.max(2*eps[sel]/3-1))],
            H_min_recorded=float(h.min()), scalar_kinetic_fraction_at_Hmin=float(vh[np.argmin(h)]**2/12/h.min()**2),
            Omega_W_at_Hmin=float(Wy[np.argmin(h)]/h.min()**2))
    return out

def main():
    with zipfile.ZipFile(CHAT14_ZIP) as z:
        res = {}
        for r in RUNS:
            summ = json.loads(z.read(CHAT14_PREFIX+'runs/'+r+'_summary.json'))
            rec = np.load(io.BytesIO(z.read(CHAT14_PREFIX+'runs/'+r+'_timeseries.npz')))['rec']
            res[r] = dict(summary=summ, analysis=analyse(rec, summ))
    checks = {
        'initial_Wy_small_all_runs': all(abs(v['analysis']['Wy_over_H0sq_initial']) < 1e-3 for v in res.values()),
        'control_without_sigma1_term_fails': all(abs(v['analysis']['control_Wy_initial_without_sigma1_term']) > 1 for v in res.values()),
        'weyl_identity_holds_better_than_wrong_factor': all(v['analysis']['weyl_identity_median_rel_residual'] <
                    0.1*v['analysis']['weyl_identity_wrongfactor_median_rel_residual'] for v in res.values()),
    }
    dump('M1_WEYL_ALONG_CHAT14.json', dict(archive=str(CHAT14_ZIP), archive_sha256=sha256(CHAT14_ZIP),
         units='Wy and H^2 in units of H0^2; s = H0 tau', runs=res, checks=checks,
         status='numerical (derived from archived floating-point trajectories; inherits their constraint limits)'))
    for r, v in res.items():
        a = v['analysis']
        print(r, 'Wy0=%.2e Wyend=%.4f max=%.4f@%.2f min=%.4f@%.2f OmegaW_end=%s idres=%.2e wrong=%.2e h_end=%.4f' % (
            a['Wy_over_H0sq_initial'], a['Wy_over_H0sq_end'], a['Wy_over_H0sq_max'], a['s_at_Wy_max'], a['Wy_over_H0sq_min'],
            a['s_at_Wy_min'], a['Omega_W_end'], a['weyl_identity_median_rel_residual'], a['weyl_identity_wrongfactor_median_rel_residual'], a['H_over_H0_end']))
        if 'collapse' in a: print('   collapse', a['collapse'])
        print('   sigma', a['sigma_initial'], a['sigma_max'], a['sigma_end'], 'up', a['tension_increase_total'], 'down', a['tension_decrease_total'])
    print(checks)

if __name__ == '__main__':
    main()
