#!/usr/bin/env python3
"""Exact algebra checks for the matched S4 action; no physical benchmark run."""
from __future__ import annotations
import argparse
import json
from pathlib import Path
import sympy as s


def run():
    passed = []
    negatives = []
    def equal(name, lhs, rhs=0):
        residue = s.simplify(s.expand(lhs-rhs))
        if residue != 0:
            raise AssertionError(f'{name}: {residue}')
        passed.append(name)
    def detect(name, residue):
        residue = s.factor(s.simplify(residue))
        if residue == 0:
            raise AssertionError(f'negative control survived: {name}')
        negatives.append({'name': name, 'nonzero_residual': str(residue)})

    x,r,z,ss = s.symbols('x r z s', positive=True)
    h=x-r
    C=1/(16*s.pi**2)
    c=h*h/2-2*z*h+s.Rational(29,15)*z*z
    P=1+(2*z-h)*ss+c*ss*ss
    equal('reference derivative of subtraction', s.diff(s.exp(-r*ss)*P,r), -c*ss**3*s.exp(-r*ss))
    equal('metric subtraction polynomial',P-z*s.diff(P,z)/2,
          1+(z-h)*ss+(h*h/2-z*h)*ss*ss)
    equal('scalar subtraction polynomial',s.diff(P,x),-ss+(h-2*z)*ss*ss)
    equal('UV action cancellation through s2',s.series(s.exp(-x*ss)*(1+2*z*ss+s.Rational(29,15)*z*z*ss*ss)-s.exp(-r*ss)*P,ss,0,3).removeO())

    V=(x*x*s.log(x/r)-3*x*x/2+2*r*x-r*r/2)/(64*s.pi**2)
    F=(x*s.log(x/r)-x+r)/(192*s.pi**2)
    for k in range(3): equal(f'potential reference match order {k}',s.diff(V,x,k).subs(x,r))
    for k in range(2): equal(f'curvature reference match order {k}',s.diff(F,x,k).subs(x,r))
    equal('flat reference trace',-4*V,-x*2*s.diff(V,x)+C*h*h/2)
    equal('flat Q',2*s.diff(V,x),C*(x*s.log(x/r)-x+r))
    equal('S4 geometric heat coefficient', (12*z)**2/72-(24*z*z)/360,s.Rational(29,15)*z*z)
    equal('full local reference derivative',s.diff(V-12*z*F+C*s.Rational(29,15)*z*z*s.log(x/r)/2,r),-C*c/(2*r))

    u,v=s.symbols('u v', positive=True)
    D=u*u/2-2*u+s.Rational(29,15)
    cc=(u-v)**2/2-2*(u-v)+s.Rational(29,15)
    Psi=s.Function('Psi')(u)
    Y=s.Function('Y')(u)
    Yprime=-((u-2)*Psi-u+s.Rational(4,3))/6
    B=-6*Y-D*s.log(v)+u*v-2*v-v*v/4
    Bu=s.diff(B,u).subs(s.diff(Y,u),Yprime)
    Bv=s.diff(B,v)
    q=(u-2)*(Psi-s.log(v))-u+v+s.Rational(4,3)
    rr=u*(u-2)*(Psi-s.log(v))-u*u+s.Rational(4,3)*u+2*u*v-2*v-v*v/2-D
    equal('spectral scalar variation',Bu,q)
    equal('spectral independent metric variation',u*Bu+v*Bv,rr)
    equal('spectral reference derivative',Bv,-cc/v)
    equal('exact matched trace after independent metric variation',rr,u*q-cc)
    equal('cross derivative integrability',s.diff(rr,u),2*q-(q-u*s.diff(q,u)-v*s.diff(q,v)))
    equal('reference current derivative',v*s.diff(q,v),-s.diff(cc,u))
    equal('regular exact-mode current point',q.subs({u:2,v:2}),s.Rational(4,3))
    equal('regular exact-mode metric point',rr.subs({u:2,v:2}),s.Rational(11,15))
    equal('current mass derivative',s.diff(q,u),Psi-s.log(v)+(u-2)*s.diff(Psi,u)-1)
    equal('current metric derivative',q-u*s.diff(q,u)-v*s.diff(q,v),-2*(Psi-s.log(v))-u*(u-2)*s.diff(Psi,u)+u-s.Rational(2,3))

    a=s.Rational(3,2)
    Zminus1=-s.bernoulli(2,a)/2
    Zminus3=-s.bernoulli(4,a)/4
    qq=u-s.Rational(9,4)
    Zzero=(Zminus3-Zminus1/4)/3+qq/24+qq*qq/12
    equal('Hurwitz zeta value at minus one',Zminus1,-s.Rational(11,24))
    equal('spectral zeta zero coefficient',Zzero,D/6)
    equal('spectral zeta residue derivative',s.diff(D/6,u),-(2-u)/6)
    # Explicit finite-part resolvent after subtracting n and (2-u)/n.
    psi_a=s.symbols('psi_a')
    fp=(Zminus1-(2-u)*psi_a-qq/2+(2-u)*(psi_a-Psi/2))/3
    equal('independent resolvent finite part',fp,((u-2)*Psi-u+s.Rational(4,3))/6)
    equal('Mellin reference polynomial finite part',s.Rational(3,4)*v*v-v*(2-u+v),u*v-2*v-v*v/4)

    # Heat coefficients independently generated by Euler--Maclaurin.
    t,n=s.symbols('t n',positive=True)
    f=(n**3-n/4)*s.exp(-t*n*n)
    aa=s.Rational(1,2) # its extra lowest term has zero degeneracy
    integral=s.exp(-t*aa*aa)*(aa*aa/(2*t)+1/(2*t*t)-1/(8*t))
    em=integral+f.subs(n,aa)/2
    for k in range(1,6):
        em-=s.bernoulli(2*k)/s.factorial(2*k)*s.diff(f,n,2*k-1).subs(n,aa)
    heat=s.series(2*t*t*s.exp(9*t/4)*em,t,0,5).removeO().expand()
    expected=[1,2,s.Rational(29,15),s.Rational(74,63),s.Rational(149,315)]
    for power,value in enumerate(expected): equal(f'heat coefficient a{power}',heat.coeff(t,power),value)

    # General finite local shifts distinguish current from density derivative.
    vv=s.Function('V')(x); ff=s.Function('F')(x); alpha=s.symbols('alpha')
    Wloc=vv-12*z*ff-144*alpha*z*z
    rholoc=Wloc-z*s.diff(Wloc,z)/2
    Qloc=2*s.diff(Wloc,x)
    equal('general local metric variation',rholoc,vv-6*z*ff)
    equal('general local scalar variation',Qloc,2*s.diff(vv,x)-24*z*s.diff(ff,x))
    equal('constant R2 stress vanishes',s.diff(rholoc,alpha))
    equal('general local cross derivative',s.diff(rholoc,x),Qloc/2-z*s.diff(Qloc,z)/4)

    detect('density incorrectly equals action density',Wloc-rholoc)
    detect('reference tracks x during scalar variation',-C*c/r)
    Qdrop=2*s.diff(vv,x)
    detect('drop curvature scalar current',s.diff(rholoc,x)-(Qdrop/2-z*s.diff(Qdrop,z)/4))
    detect('double count finite F metric source',-6*z*ff)
    wrong_fp=((u-2)*Psi-u-s.Rational(2,3))/6
    detect('replace resolvent constant by wrong -2/3',fp-wrong_fp)
    detect('flip scalar current sign',s.diff(rholoc,x)-(-Qloc/2+z*s.diff(Qloc,z)/4))
    return {'kind':'exact symbolic action/source checks','assertions':len(passed),'passed':passed,
            'negative_controls_detected':len(negatives),'negative_controls':negatives,
            'no_physical_numerical_benchmark':True,'sympy_version':s.__version__}

if __name__=='__main__':
    parser=argparse.ArgumentParser()
    parser.add_argument('--output',type=Path)
    args=parser.parse_args()
    result=run()
    encoded=json.dumps(result,indent=2)+'\n'
    if args.output:
        args.output.parent.mkdir(parents=True,exist_ok=True)
        args.output.write_text(encoded)
    print(encoded,end='')
